// 이 파일은 scripts/generate-data.mjs 가 문장표에서 자동 생성한다. 직접 수정 금지.
// 키: `${series}-${subject}-${tense}-${form}` — 총 633문장 (한국어 해석 633개).
export const SUBJECTS = ["I","she","he","it","we","they"];
export const SETS = [
  {
    "id": "be",
    "label": "be동사",
    "tenses": [
      "present",
      "past",
      "will",
      "goingto"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "late",
      "she": "lovely",
      "he": "busy",
      "it": "cold",
      "we": "ready",
      "they": "here"
    },
    "futurePred": {
      "she": "fine"
    }
  },
  {
    "id": "verb",
    "label": "일반동사",
    "tenses": [
      "present",
      "past",
      "will",
      "goingto"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "know you",
      "she": "like it",
      "he": "know it",
      "it": "work",
      "we": "need it",
      "they": "like it"
    },
    "futurePred": {
      "I": "see you",
      "he": "come"
    }
  },
  {
    "id": "prog",
    "label": "진행",
    "tenses": [
      "present",
      "past"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "working",
      "she": "coming",
      "he": "waiting",
      "it": "raining",
      "we": "waiting",
      "they": "coming"
    },
    "futurePred": {}
  },
  {
    "id": "pass",
    "label": "수동",
    "tenses": [
      "present",
      "past"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "invited",
      "she": "invited",
      "he": "invited",
      "it": "broken",
      "we": "invited",
      "they": "invited"
    },
    "futurePred": {}
  },
  {
    "id": "passget",
    "label": "get 수동",
    "tenses": [
      "present",
      "past"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "invited",
      "she": "invited",
      "he": "invited",
      "it": "broken",
      "we": "invited",
      "they": "invited"
    },
    "futurePred": {}
  },
  {
    "id": "keep",
    "label": "keep -ing",
    "tenses": [
      "present",
      "past"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "working",
      "she": "coming",
      "he": "waiting",
      "it": "raining",
      "we": "waiting",
      "they": "coming"
    },
    "futurePred": {}
  },
  {
    "id": "perfbe",
    "label": "완료 be",
    "tenses": [
      "perf"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "busy",
      "she": "busy",
      "he": "busy",
      "it": "cold",
      "we": "busy",
      "they": "here"
    },
    "futurePred": {}
  },
  {
    "id": "perfverb",
    "label": "완료 일반",
    "tenses": [
      "perf"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "seen it",
      "she": "seen it",
      "he": "seen it",
      "it": "worked",
      "we": "seen it",
      "they": "seen it"
    },
    "futurePred": {}
  },
  {
    "id": "can",
    "label": "can",
    "tenses": [
      "modal"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "do it",
      "she": "come",
      "he": "help",
      "it": "wait",
      "we": "go",
      "they": "help"
    },
    "futurePred": {}
  },
  {
    "id": "should",
    "label": "should",
    "tenses": [
      "modal"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "go",
      "she": "come",
      "he": "wait",
      "it": "be ready",
      "we": "go",
      "they": "come"
    },
    "futurePred": {}
  },
  {
    "id": "whbe",
    "label": "의문사 be",
    "tenses": [
      "wh"
    ],
    "forms": [
      "where",
      "when",
      "why"
    ],
    "formHeads": [
      "Where",
      "When",
      "Why"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "wh",
      "she": "wh",
      "he": "wh",
      "it": "wh",
      "we": "wh",
      "they": "wh"
    },
    "futurePred": {},
    "predByForm": {
      "where": {
        "I": "",
        "she": "",
        "he": "",
        "it": "",
        "we": "",
        "they": ""
      },
      "when": {
        "I": "free",
        "she": "coming",
        "he": "coming",
        "it": "",
        "we": "leaving",
        "they": "coming"
      },
      "why": {
        "I": "here",
        "she": "late",
        "he": "angry",
        "it": "cold",
        "we": "here",
        "they": "here"
      }
    }
  },
  {
    "id": "whdo",
    "label": "의문사 do",
    "tenses": [
      "wh"
    ],
    "forms": [
      "what",
      "how",
      "why"
    ],
    "formHeads": [
      "What",
      "How",
      "Why"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "wh",
      "she": "wh",
      "he": "wh",
      "it": "wh",
      "we": "wh",
      "they": "wh"
    },
    "futurePred": {},
    "predByForm": {
      "what": {
        "I": "do",
        "she": "want",
        "he": "want",
        "it": "mean",
        "we": "need",
        "they": "want"
      },
      "how": {
        "I": "know",
        "she": "know",
        "he": "do it",
        "it": "work",
        "we": "get there",
        "they": "know"
      },
      "why": {
        "I": "need it",
        "she": "like it",
        "he": "need it",
        "it": "matter",
        "we": "need it",
        "they": "like it"
      }
    }
  },
  {
    "id": "adjpos",
    "label": "형용사 위치",
    "tenses": [
      "pos"
    ],
    "forms": [
      "comp",
      "attr"
    ],
    "formHeads": [
      "보어",
      "명사 앞"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "busy",
      "she": "kind",
      "he": "tall",
      "it": "small",
      "we": "young",
      "they": "famous"
    },
    "futurePred": {},
    "predByForm": {
      "comp": {
        "I": "busy",
        "she": "kind",
        "he": "tall",
        "it": "small",
        "we": "young",
        "they": "famous"
      },
      "attr": {
        "I": "busy student",
        "she": "kind girl",
        "he": "tall boy",
        "it": "small apple",
        "we": "young students",
        "they": "famous singers"
      }
    }
  },
  {
    "id": "quant",
    "label": "수량 표현",
    "tenses": [
      "many",
      "afew",
      "few"
    ],
    "forms": [
      "cnt",
      "unc"
    ],
    "formHeads": [
      "셀 수 있는",
      "셀 수 없는"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "books",
      "she": "friends",
      "he": "pens",
      "it": "colors",
      "we": "chairs",
      "they": "questions"
    },
    "futurePred": {},
    "predByForm": {
      "cnt": {
        "I": "books",
        "she": "friends",
        "he": "pens",
        "it": "colors",
        "we": "chairs",
        "they": "questions"
      },
      "unc": {
        "I": "time",
        "she": "money",
        "he": "bread",
        "it": "space",
        "we": "work",
        "they": "homework"
      }
    }
  },
  {
    "id": "freq",
    "label": "빈도부사",
    "tenses": [
      "often",
      "usually",
      "never"
    ],
    "forms": [
      "gen",
      "be",
      "modal"
    ],
    "formHeads": [
      "일반동사 앞",
      "be동사 뒤",
      "조동사 뒤"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "soccer",
      "she": "there",
      "he": "breakfast",
      "it": "well",
      "we": "here",
      "they": "late"
    },
    "futurePred": {},
    "predByForm": {
      "gen": {
        "I": "play soccer",
        "she": "goes there",
        "he": "eats breakfast",
        "it": "works well",
        "we": "meet here",
        "they": "come late"
      },
      "be": {
        "I": "tired",
        "she": "busy",
        "he": "late",
        "it": "cold",
        "we": "ready",
        "they": "happy"
      },
      "modal": {
        "I": "help you",
        "she": "come early",
        "he": "remember it",
        "it": "start early",
        "we": "go together",
        "they": "win the game"
      }
    }
  },
  {
    "id": "cmpadj",
    "label": "형용사 비교",
    "tenses": [
      "base",
      "equality",
      "comparative",
      "superlative"
    ],
    "forms": [
      "aff"
    ],
    "formHeads": [
      "문장"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "tall",
      "she": "smart",
      "he": "busy",
      "it": "interesting",
      "we": "happy",
      "they": "popular"
    },
    "futurePred": {},
    "predByTense": {
      "base": {
        "I": "tall",
        "she": "smart",
        "he": "busy",
        "it": "interesting",
        "we": "happy",
        "they": "popular"
      },
      "equality": {
        "I": "tall · Mina",
        "she": "smart · Mina",
        "he": "busy · Jack",
        "it": "interesting · that book",
        "we": "happy · them",
        "they": "popular · us"
      },
      "comparative": {
        "I": "tall · Mina",
        "she": "smart · Mina",
        "he": "busy · Jack",
        "it": "interesting · that book",
        "we": "happy · them",
        "they": "popular · us"
      },
      "superlative": {
        "I": "tall · my class",
        "she": "smart · her class",
        "he": "busy · his team",
        "it": "interesting · the three",
        "we": "happy · our school",
        "they": "popular · our school"
      }
    }
  },
  {
    "id": "cmpadv",
    "label": "부사 비교",
    "tenses": [
      "base",
      "equality",
      "comparative",
      "superlative"
    ],
    "forms": [
      "aff"
    ],
    "formHeads": [
      "문장"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "hard",
      "she": "carefully",
      "he": "fast",
      "it": "quickly",
      "we": "early",
      "they": "loudly"
    },
    "futurePred": {},
    "predByTense": {
      "base": {
        "I": "hard",
        "she": "carefully",
        "he": "fast",
        "it": "quickly",
        "we": "early",
        "they": "loudly"
      },
      "equality": {
        "I": "hard · Mina",
        "she": "carefully · Mina",
        "he": "fast · Jack",
        "it": "quickly · that one",
        "we": "early · them",
        "they": "loudly · us"
      },
      "comparative": {
        "I": "hard · Mina",
        "she": "carefully · Mina",
        "he": "fast · Jack",
        "it": "quickly · that one",
        "we": "early · them",
        "they": "loudly · us"
      },
      "superlative": {
        "I": "hard · my class",
        "she": "carefully · her team",
        "he": "fast · the three",
        "it": "quickly · the three",
        "we": "early · our class",
        "they": "loudly · the group"
      }
    }
  },
  {
    "id": "adjpron",
    "label": "대명사 뒤",
    "tenses": [
      "pos"
    ],
    "forms": [
      "np",
      "pron"
    ],
    "formHeads": [
      "명사구",
      "대명사 뒤"
    ],
    "subjects": [
      "something",
      "somebody",
      "someone",
      "anything",
      "nothing",
      "everything"
    ],
    "cards": false,
    "pred": {
      "something": "cold",
      "somebody": "strong",
      "someone": "strange",
      "anything": "expensive",
      "nothing": "special",
      "everything": "sweet"
    },
    "futurePred": {},
    "predByForm": {
      "np": {
        "something": "cold drink",
        "somebody": "strong helper",
        "someone": "strange man",
        "anything": "expensive bag",
        "nothing": "special reason",
        "everything": "sweet food"
      },
      "pron": {
        "something": "cold",
        "somebody": "strong",
        "someone": "strange",
        "anything": "expensive",
        "nothing": "special",
        "everything": "sweet"
      }
    }
  },
  {
    "id": "quantsome",
    "label": "some / any",
    "tenses": [
      "there",
      "have"
    ],
    "forms": [
      "aff",
      "neg",
      "q"
    ],
    "formHeads": [
      "긍정",
      "부정",
      "의문"
    ],
    "subjects": [
      "books",
      "water",
      "students",
      "money",
      "questions",
      "time"
    ],
    "cards": false,
    "pred": {
      "books": "books",
      "water": "water",
      "students": "students",
      "money": "money",
      "questions": "questions",
      "time": "time"
    },
    "futurePred": {}
  },
  {
    "id": "adv",
    "label": "일반 부사",
    "tenses": [
      "adv"
    ],
    "forms": [
      "adj",
      "advb"
    ],
    "formHeads": [
      "형용사",
      "부사"
    ],
    "subjects": [
      "I",
      "she",
      "he",
      "it",
      "we",
      "they"
    ],
    "cards": false,
    "pred": {
      "I": "slow",
      "she": "careful",
      "he": "quick",
      "it": "loud",
      "we": "quiet",
      "they": "kind"
    },
    "futurePred": {},
    "predByForm": {
      "adj": {
        "I": "slow",
        "she": "careful",
        "he": "quick",
        "it": "loud",
        "we": "quiet",
        "they": "kind"
      },
      "advb": {
        "I": "walk slowly",
        "she": "drives carefully",
        "he": "runs quickly",
        "it": "rings loudly",
        "we": "speak quietly",
        "they": "smile kindly"
      }
    }
  },
  {
    "id": "warmup",
    "label": "형태 워밍업",
    "tenses": [
      "base",
      "comparative",
      "superlative"
    ],
    "forms": [
      "word"
    ],
    "formHeads": [
      "형태"
    ],
    "subjects": [
      "tall",
      "nice",
      "happy",
      "big",
      "beautiful",
      "good",
      "bad",
      "many",
      "little"
    ],
    "cards": true,
    "pred": {
      "tall": "",
      "nice": "",
      "happy": "",
      "big": "",
      "beautiful": "",
      "good": "",
      "bad": "",
      "many": "",
      "little": ""
    },
    "futurePred": {}
  }
];
export const SENTENCES = {
  "be-I-present-aff": "I am late.",
  "be-I-present-neg": "I'm not late.",
  "be-I-present-q": "Am I late?",
  "be-she-present-aff": "She is lovely.",
  "be-she-present-neg": "She isn't lovely.",
  "be-she-present-q": "Is she lovely?",
  "be-he-present-aff": "He is busy.",
  "be-he-present-neg": "He isn't busy.",
  "be-he-present-q": "Is he busy?",
  "be-it-present-aff": "It is cold.",
  "be-it-present-neg": "It isn't cold.",
  "be-it-present-q": "Is it cold?",
  "be-we-present-aff": "We are ready.",
  "be-we-present-neg": "We aren't ready.",
  "be-we-present-q": "Are we ready?",
  "be-they-present-aff": "They are here.",
  "be-they-present-neg": "They aren't here.",
  "be-they-present-q": "Are they here?",
  "be-I-past-aff": "I was late.",
  "be-I-past-neg": "I wasn't late.",
  "be-I-past-q": "Was I late?",
  "be-she-past-aff": "She was lovely.",
  "be-she-past-neg": "She wasn't lovely.",
  "be-she-past-q": "Was she lovely?",
  "be-he-past-aff": "He was busy.",
  "be-he-past-neg": "He wasn't busy.",
  "be-he-past-q": "Was he busy?",
  "be-it-past-aff": "It was cold.",
  "be-it-past-neg": "It wasn't cold.",
  "be-it-past-q": "Was it cold?",
  "be-we-past-aff": "We were ready.",
  "be-we-past-neg": "We weren't ready.",
  "be-we-past-q": "Were we ready?",
  "be-they-past-aff": "They were here.",
  "be-they-past-neg": "They weren't here.",
  "be-they-past-q": "Were they here?",
  "be-I-will-aff": "I'll be late.",
  "be-I-will-neg": "I won't be late.",
  "be-I-will-q": "Will I be late?",
  "be-she-will-aff": "She'll be fine.",
  "be-she-will-neg": "She won't be fine.",
  "be-she-will-q": "Will she be fine?",
  "be-he-will-aff": "He'll be busy.",
  "be-he-will-neg": "He won't be busy.",
  "be-he-will-q": "Will he be busy?",
  "be-it-will-aff": "It'll be cold.",
  "be-it-will-neg": "It won't be cold.",
  "be-it-will-q": "Will it be cold?",
  "be-we-will-aff": "We'll be ready.",
  "be-we-will-neg": "We won't be ready.",
  "be-we-will-q": "Will we be ready?",
  "be-they-will-aff": "They'll be here.",
  "be-they-will-neg": "They won't be here.",
  "be-they-will-q": "Will they be here?",
  "be-I-goingto-aff": "I'm going to be late.",
  "be-I-goingto-neg": "I'm not going to be late.",
  "be-I-goingto-q": "Am I going to be late?",
  "be-she-goingto-aff": "She's going to be fine.",
  "be-she-goingto-neg": "She isn't going to be fine.",
  "be-she-goingto-q": "Is she going to be fine?",
  "be-he-goingto-aff": "He's going to be busy.",
  "be-he-goingto-neg": "He isn't going to be busy.",
  "be-he-goingto-q": "Is he going to be busy?",
  "be-it-goingto-aff": "It's going to be cold.",
  "be-it-goingto-neg": "It isn't going to be cold.",
  "be-it-goingto-q": "Is it going to be cold?",
  "be-we-goingto-aff": "We're going to be ready.",
  "be-we-goingto-neg": "We aren't going to be ready.",
  "be-we-goingto-q": "Are we going to be ready?",
  "be-they-goingto-aff": "They're going to be here.",
  "be-they-goingto-neg": "They aren't going to be here.",
  "be-they-goingto-q": "Are they going to be here?",
  "verb-I-present-aff": "I know you.",
  "verb-I-present-neg": "I don't know you.",
  "verb-I-present-q": "Do I know you?",
  "verb-she-present-aff": "She likes it.",
  "verb-she-present-neg": "She doesn't like it.",
  "verb-she-present-q": "Does she like it?",
  "verb-he-present-aff": "He knows it.",
  "verb-he-present-neg": "He doesn't know it.",
  "verb-he-present-q": "Does he know it?",
  "verb-it-present-aff": "It works.",
  "verb-it-present-neg": "It doesn't work.",
  "verb-it-present-q": "Does it work?",
  "verb-we-present-aff": "We need it.",
  "verb-we-present-neg": "We don't need it.",
  "verb-we-present-q": "Do we need it?",
  "verb-they-present-aff": "They like it.",
  "verb-they-present-neg": "They don't like it.",
  "verb-they-present-q": "Do they like it?",
  "verb-I-past-aff": "I knew you.",
  "verb-I-past-neg": "I didn't know you.",
  "verb-I-past-q": "Did I know you?",
  "verb-she-past-aff": "She liked it.",
  "verb-she-past-neg": "She didn't like it.",
  "verb-she-past-q": "Did she like it?",
  "verb-he-past-aff": "He knew it.",
  "verb-he-past-neg": "He didn't know it.",
  "verb-he-past-q": "Did he know it?",
  "verb-it-past-aff": "It worked.",
  "verb-it-past-neg": "It didn't work.",
  "verb-it-past-q": "Did it work?",
  "verb-we-past-aff": "We needed it.",
  "verb-we-past-neg": "We didn't need it.",
  "verb-we-past-q": "Did we need it?",
  "verb-they-past-aff": "They liked it.",
  "verb-they-past-neg": "They didn't like it.",
  "verb-they-past-q": "Did they like it?",
  "verb-I-will-aff": "I'll see you.",
  "verb-I-will-neg": "I won't see you.",
  "verb-I-will-q": "Will I see you?",
  "verb-she-will-aff": "She'll like it.",
  "verb-she-will-neg": "She won't like it.",
  "verb-she-will-q": "Will she like it?",
  "verb-he-will-aff": "He'll come.",
  "verb-he-will-neg": "He won't come.",
  "verb-he-will-q": "Will he come?",
  "verb-it-will-aff": "It'll work.",
  "verb-it-will-neg": "It won't work.",
  "verb-it-will-q": "Will it work?",
  "verb-we-will-aff": "We'll need it.",
  "verb-we-will-neg": "We won't need it.",
  "verb-we-will-q": "Will we need it?",
  "verb-they-will-aff": "They'll like it.",
  "verb-they-will-neg": "They won't like it.",
  "verb-they-will-q": "Will they like it?",
  "verb-I-goingto-aff": "I'm going to see you.",
  "verb-I-goingto-neg": "I'm not going to see you.",
  "verb-I-goingto-q": "Am I going to see you?",
  "verb-she-goingto-aff": "She's going to like it.",
  "verb-she-goingto-neg": "She isn't going to like it.",
  "verb-she-goingto-q": "Is she going to like it?",
  "verb-he-goingto-aff": "He's going to come.",
  "verb-he-goingto-neg": "He isn't going to come.",
  "verb-he-goingto-q": "Is he going to come?",
  "verb-it-goingto-aff": "It's going to work.",
  "verb-it-goingto-neg": "It isn't going to work.",
  "verb-it-goingto-q": "Is it going to work?",
  "verb-we-goingto-aff": "We're going to need it.",
  "verb-we-goingto-neg": "We aren't going to need it.",
  "verb-we-goingto-q": "Are we going to need it?",
  "verb-they-goingto-aff": "They're going to like it.",
  "verb-they-goingto-neg": "They aren't going to like it.",
  "verb-they-goingto-q": "Are they going to like it?",
  "prog-I-present-aff": "I'm working.",
  "prog-I-present-neg": "I'm not working.",
  "prog-I-present-q": "Am I working?",
  "prog-she-present-aff": "She's coming.",
  "prog-she-present-neg": "She isn't coming.",
  "prog-she-present-q": "Is she coming?",
  "prog-he-present-aff": "He's waiting.",
  "prog-he-present-neg": "He isn't waiting.",
  "prog-he-present-q": "Is he waiting?",
  "prog-it-present-aff": "It's raining.",
  "prog-it-present-neg": "It isn't raining.",
  "prog-it-present-q": "Is it raining?",
  "prog-we-present-aff": "We're waiting.",
  "prog-we-present-neg": "We aren't waiting.",
  "prog-we-present-q": "Are we waiting?",
  "prog-they-present-aff": "They're coming.",
  "prog-they-present-neg": "They aren't coming.",
  "prog-they-present-q": "Are they coming?",
  "prog-I-past-aff": "I was working.",
  "prog-I-past-neg": "I wasn't working.",
  "prog-I-past-q": "Was I working?",
  "prog-she-past-aff": "She was coming.",
  "prog-she-past-neg": "She wasn't coming.",
  "prog-she-past-q": "Was she coming?",
  "prog-he-past-aff": "He was waiting.",
  "prog-he-past-neg": "He wasn't waiting.",
  "prog-he-past-q": "Was he waiting?",
  "prog-it-past-aff": "It was raining.",
  "prog-it-past-neg": "It wasn't raining.",
  "prog-it-past-q": "Was it raining?",
  "prog-we-past-aff": "We were waiting.",
  "prog-we-past-neg": "We weren't waiting.",
  "prog-we-past-q": "Were we waiting?",
  "prog-they-past-aff": "They were coming.",
  "prog-they-past-neg": "They weren't coming.",
  "prog-they-past-q": "Were they coming?",
  "pass-I-present-aff": "I am invited.",
  "pass-I-present-neg": "I'm not invited.",
  "pass-I-present-q": "Am I invited?",
  "pass-she-present-aff": "She is invited.",
  "pass-she-present-neg": "She isn't invited.",
  "pass-she-present-q": "Is she invited?",
  "pass-he-present-aff": "He is invited.",
  "pass-he-present-neg": "He isn't invited.",
  "pass-he-present-q": "Is he invited?",
  "pass-it-present-aff": "It is broken.",
  "pass-it-present-neg": "It isn't broken.",
  "pass-it-present-q": "Is it broken?",
  "pass-we-present-aff": "We are invited.",
  "pass-we-present-neg": "We aren't invited.",
  "pass-we-present-q": "Are we invited?",
  "pass-they-present-aff": "They are invited.",
  "pass-they-present-neg": "They aren't invited.",
  "pass-they-present-q": "Are they invited?",
  "pass-I-past-aff": "I was invited.",
  "pass-I-past-neg": "I wasn't invited.",
  "pass-I-past-q": "Was I invited?",
  "pass-she-past-aff": "She was invited.",
  "pass-she-past-neg": "She wasn't invited.",
  "pass-she-past-q": "Was she invited?",
  "pass-he-past-aff": "He was invited.",
  "pass-he-past-neg": "He wasn't invited.",
  "pass-he-past-q": "Was he invited?",
  "pass-it-past-aff": "It was broken.",
  "pass-it-past-neg": "It wasn't broken.",
  "pass-it-past-q": "Was it broken?",
  "pass-we-past-aff": "We were invited.",
  "pass-we-past-neg": "We weren't invited.",
  "pass-we-past-q": "Were we invited?",
  "pass-they-past-aff": "They were invited.",
  "pass-they-past-neg": "They weren't invited.",
  "pass-they-past-q": "Were they invited?",
  "passget-I-present-aff": "I get invited.",
  "passget-I-present-neg": "I don't get invited.",
  "passget-I-present-q": "Do I get invited?",
  "passget-she-present-aff": "She gets invited.",
  "passget-she-present-neg": "She doesn't get invited.",
  "passget-she-present-q": "Does she get invited?",
  "passget-he-present-aff": "He gets invited.",
  "passget-he-present-neg": "He doesn't get invited.",
  "passget-he-present-q": "Does he get invited?",
  "passget-it-present-aff": "It gets broken.",
  "passget-it-present-neg": "It doesn't get broken.",
  "passget-it-present-q": "Does it get broken?",
  "passget-we-present-aff": "We get invited.",
  "passget-we-present-neg": "We don't get invited.",
  "passget-we-present-q": "Do we get invited?",
  "passget-they-present-aff": "They get invited.",
  "passget-they-present-neg": "They don't get invited.",
  "passget-they-present-q": "Do they get invited?",
  "passget-I-past-aff": "I got invited.",
  "passget-I-past-neg": "I didn't get invited.",
  "passget-I-past-q": "Did I get invited?",
  "passget-she-past-aff": "She got invited.",
  "passget-she-past-neg": "She didn't get invited.",
  "passget-she-past-q": "Did she get invited?",
  "passget-he-past-aff": "He got invited.",
  "passget-he-past-neg": "He didn't get invited.",
  "passget-he-past-q": "Did he get invited?",
  "passget-it-past-aff": "It got broken.",
  "passget-it-past-neg": "It didn't get broken.",
  "passget-it-past-q": "Did it get broken?",
  "passget-we-past-aff": "We got invited.",
  "passget-we-past-neg": "We didn't get invited.",
  "passget-we-past-q": "Did we get invited?",
  "passget-they-past-aff": "They got invited.",
  "passget-they-past-neg": "They didn't get invited.",
  "passget-they-past-q": "Did they get invited?",
  "keep-I-present-aff": "I keep working.",
  "keep-I-present-neg": "I don't keep working.",
  "keep-I-present-q": "Do I keep working?",
  "keep-she-present-aff": "She keeps coming.",
  "keep-she-present-neg": "She doesn't keep coming.",
  "keep-she-present-q": "Does she keep coming?",
  "keep-he-present-aff": "He keeps waiting.",
  "keep-he-present-neg": "He doesn't keep waiting.",
  "keep-he-present-q": "Does he keep waiting?",
  "keep-it-present-aff": "It keeps raining.",
  "keep-it-present-neg": "It doesn't keep raining.",
  "keep-it-present-q": "Does it keep raining?",
  "keep-we-present-aff": "We keep waiting.",
  "keep-we-present-neg": "We don't keep waiting.",
  "keep-we-present-q": "Do we keep waiting?",
  "keep-they-present-aff": "They keep coming.",
  "keep-they-present-neg": "They don't keep coming.",
  "keep-they-present-q": "Do they keep coming?",
  "keep-I-past-aff": "I kept working.",
  "keep-I-past-neg": "I didn't keep working.",
  "keep-I-past-q": "Did I keep working?",
  "keep-she-past-aff": "She kept coming.",
  "keep-she-past-neg": "She didn't keep coming.",
  "keep-she-past-q": "Did she keep coming?",
  "keep-he-past-aff": "He kept waiting.",
  "keep-he-past-neg": "He didn't keep waiting.",
  "keep-he-past-q": "Did he keep waiting?",
  "keep-it-past-aff": "It kept raining.",
  "keep-it-past-neg": "It didn't keep raining.",
  "keep-it-past-q": "Did it keep raining?",
  "keep-we-past-aff": "We kept waiting.",
  "keep-we-past-neg": "We didn't keep waiting.",
  "keep-we-past-q": "Did we keep waiting?",
  "keep-they-past-aff": "They kept coming.",
  "keep-they-past-neg": "They didn't keep coming.",
  "keep-they-past-q": "Did they keep coming?",
  "perfbe-I-perf-aff": "I have been busy.",
  "perfbe-I-perf-neg": "I haven't been busy.",
  "perfbe-I-perf-q": "Have I been busy?",
  "perfbe-she-perf-aff": "She has been busy.",
  "perfbe-she-perf-neg": "She hasn't been busy.",
  "perfbe-she-perf-q": "Has she been busy?",
  "perfbe-he-perf-aff": "He has been busy.",
  "perfbe-he-perf-neg": "He hasn't been busy.",
  "perfbe-he-perf-q": "Has he been busy?",
  "perfbe-it-perf-aff": "It has been cold.",
  "perfbe-it-perf-neg": "It hasn't been cold.",
  "perfbe-it-perf-q": "Has it been cold?",
  "perfbe-we-perf-aff": "We have been busy.",
  "perfbe-we-perf-neg": "We haven't been busy.",
  "perfbe-we-perf-q": "Have we been busy?",
  "perfbe-they-perf-aff": "They have been here.",
  "perfbe-they-perf-neg": "They haven't been here.",
  "perfbe-they-perf-q": "Have they been here?",
  "perfverb-I-perf-aff": "I have seen it.",
  "perfverb-I-perf-neg": "I haven't seen it.",
  "perfverb-I-perf-q": "Have I seen it?",
  "perfverb-she-perf-aff": "She has seen it.",
  "perfverb-she-perf-neg": "She hasn't seen it.",
  "perfverb-she-perf-q": "Has she seen it?",
  "perfverb-he-perf-aff": "He has seen it.",
  "perfverb-he-perf-neg": "He hasn't seen it.",
  "perfverb-he-perf-q": "Has he seen it?",
  "perfverb-it-perf-aff": "It has worked.",
  "perfverb-it-perf-neg": "It hasn't worked.",
  "perfverb-it-perf-q": "Has it worked?",
  "perfverb-we-perf-aff": "We have seen it.",
  "perfverb-we-perf-neg": "We haven't seen it.",
  "perfverb-we-perf-q": "Have we seen it?",
  "perfverb-they-perf-aff": "They have seen it.",
  "perfverb-they-perf-neg": "They haven't seen it.",
  "perfverb-they-perf-q": "Have they seen it?",
  "can-I-modal-aff": "I can do it.",
  "can-I-modal-neg": "I can't do it.",
  "can-I-modal-q": "Can I do it?",
  "can-she-modal-aff": "She can come.",
  "can-she-modal-neg": "She can't come.",
  "can-she-modal-q": "Can she come?",
  "can-he-modal-aff": "He can help.",
  "can-he-modal-neg": "He can't help.",
  "can-he-modal-q": "Can he help?",
  "can-it-modal-aff": "It can wait.",
  "can-it-modal-neg": "It can't wait.",
  "can-it-modal-q": "Can it wait?",
  "can-we-modal-aff": "We can go.",
  "can-we-modal-neg": "We can't go.",
  "can-we-modal-q": "Can we go?",
  "can-they-modal-aff": "They can help.",
  "can-they-modal-neg": "They can't help.",
  "can-they-modal-q": "Can they help?",
  "should-I-modal-aff": "I should go.",
  "should-I-modal-neg": "I shouldn't go.",
  "should-I-modal-q": "Should I go?",
  "should-she-modal-aff": "She should come.",
  "should-she-modal-neg": "She shouldn't come.",
  "should-she-modal-q": "Should she come?",
  "should-he-modal-aff": "He should wait.",
  "should-he-modal-neg": "He shouldn't wait.",
  "should-he-modal-q": "Should he wait?",
  "should-it-modal-aff": "It should be ready.",
  "should-it-modal-neg": "It shouldn't be ready.",
  "should-it-modal-q": "Should it be ready?",
  "should-we-modal-aff": "We should go.",
  "should-we-modal-neg": "We shouldn't go.",
  "should-we-modal-q": "Should we go?",
  "should-they-modal-aff": "They should come.",
  "should-they-modal-neg": "They shouldn't come.",
  "should-they-modal-q": "Should they come?",
  "whbe-I-wh-where": "Where am I?",
  "whbe-I-wh-when": "When am I free?",
  "whbe-I-wh-why": "Why am I here?",
  "whbe-she-wh-where": "Where is she?",
  "whbe-she-wh-when": "When is she coming?",
  "whbe-she-wh-why": "Why is she late?",
  "whbe-he-wh-where": "Where is he?",
  "whbe-he-wh-when": "When is he coming?",
  "whbe-he-wh-why": "Why is he angry?",
  "whbe-it-wh-where": "Where is it?",
  "whbe-it-wh-when": "When is it?",
  "whbe-it-wh-why": "Why is it cold?",
  "whbe-we-wh-where": "Where are we?",
  "whbe-we-wh-when": "When are we leaving?",
  "whbe-we-wh-why": "Why are we here?",
  "whbe-they-wh-where": "Where are they?",
  "whbe-they-wh-when": "When are they coming?",
  "whbe-they-wh-why": "Why are they here?",
  "whdo-I-wh-what": "What do I do?",
  "whdo-I-wh-how": "How do I know?",
  "whdo-I-wh-why": "Why do I need it?",
  "whdo-she-wh-what": "What does she want?",
  "whdo-she-wh-how": "How does she know?",
  "whdo-she-wh-why": "Why does she like it?",
  "whdo-he-wh-what": "What does he want?",
  "whdo-he-wh-how": "How does he do it?",
  "whdo-he-wh-why": "Why does he need it?",
  "whdo-it-wh-what": "What does it mean?",
  "whdo-it-wh-how": "How does it work?",
  "whdo-it-wh-why": "Why does it matter?",
  "whdo-we-wh-what": "What do we need?",
  "whdo-we-wh-how": "How do we get there?",
  "whdo-we-wh-why": "Why do we need it?",
  "whdo-they-wh-what": "What do they want?",
  "whdo-they-wh-how": "How do they know?",
  "whdo-they-wh-why": "Why do they like it?",
  "adjpos-I-pos-comp": "I am busy.",
  "adjpos-I-pos-attr": "I am a busy student.",
  "adjpos-she-pos-comp": "She is kind.",
  "adjpos-she-pos-attr": "She is a kind girl.",
  "adjpos-he-pos-comp": "He is tall.",
  "adjpos-he-pos-attr": "He is a tall boy.",
  "adjpos-it-pos-comp": "It is small.",
  "adjpos-it-pos-attr": "It is a small apple.",
  "adjpos-we-pos-comp": "We are young.",
  "adjpos-we-pos-attr": "We are young students.",
  "adjpos-they-pos-comp": "They are famous.",
  "adjpos-they-pos-attr": "They are famous singers.",
  "quant-I-many-cnt": "I have many books.",
  "quant-I-many-unc": "I have much time.",
  "quant-she-many-cnt": "She has many friends.",
  "quant-she-many-unc": "She has much money.",
  "quant-he-many-cnt": "He has many pens.",
  "quant-he-many-unc": "He has much bread.",
  "quant-it-many-cnt": "It has many colors.",
  "quant-it-many-unc": "It has much space.",
  "quant-we-many-cnt": "We have many chairs.",
  "quant-we-many-unc": "We have much work.",
  "quant-they-many-cnt": "They have many questions.",
  "quant-they-many-unc": "They have much homework.",
  "quant-I-afew-cnt": "I have a few books.",
  "quant-I-afew-unc": "I have a little time.",
  "quant-she-afew-cnt": "She has a few friends.",
  "quant-she-afew-unc": "She has a little money.",
  "quant-he-afew-cnt": "He has a few pens.",
  "quant-he-afew-unc": "He has a little bread.",
  "quant-it-afew-cnt": "It has a few colors.",
  "quant-it-afew-unc": "It has a little space.",
  "quant-we-afew-cnt": "We have a few chairs.",
  "quant-we-afew-unc": "We have a little work.",
  "quant-they-afew-cnt": "They have a few questions.",
  "quant-they-afew-unc": "They have a little homework.",
  "quant-I-few-cnt": "I have few books.",
  "quant-I-few-unc": "I have little time.",
  "quant-she-few-cnt": "She has few friends.",
  "quant-she-few-unc": "She has little money.",
  "quant-he-few-cnt": "He has few pens.",
  "quant-he-few-unc": "He has little bread.",
  "quant-it-few-cnt": "It has few colors.",
  "quant-it-few-unc": "It has little space.",
  "quant-we-few-cnt": "We have few chairs.",
  "quant-we-few-unc": "We have little work.",
  "quant-they-few-cnt": "They have few questions.",
  "quant-they-few-unc": "They have little homework.",
  "freq-I-often-gen": "I often play soccer.",
  "freq-I-often-be": "I am often tired.",
  "freq-I-often-modal": "I can often help you.",
  "freq-she-often-gen": "She often goes there.",
  "freq-she-often-be": "She is often busy.",
  "freq-she-often-modal": "She can often come early.",
  "freq-he-often-gen": "He often eats breakfast.",
  "freq-he-often-be": "He is often late.",
  "freq-he-often-modal": "He can often remember it.",
  "freq-it-often-gen": "It often works well.",
  "freq-it-often-be": "It is often cold.",
  "freq-it-often-modal": "It can often start early.",
  "freq-we-often-gen": "We often meet here.",
  "freq-we-often-be": "We are often ready.",
  "freq-we-often-modal": "We can often go together.",
  "freq-they-often-gen": "They often come late.",
  "freq-they-often-be": "They are often happy.",
  "freq-they-often-modal": "They can often win the game.",
  "freq-I-usually-gen": "I usually play soccer.",
  "freq-I-usually-be": "I am usually tired.",
  "freq-I-usually-modal": "I can usually help you.",
  "freq-she-usually-gen": "She usually goes there.",
  "freq-she-usually-be": "She is usually busy.",
  "freq-she-usually-modal": "She can usually come early.",
  "freq-he-usually-gen": "He usually eats breakfast.",
  "freq-he-usually-be": "He is usually late.",
  "freq-he-usually-modal": "He can usually remember it.",
  "freq-it-usually-gen": "It usually works well.",
  "freq-it-usually-be": "It is usually cold.",
  "freq-it-usually-modal": "It can usually start early.",
  "freq-we-usually-gen": "We usually meet here.",
  "freq-we-usually-be": "We are usually ready.",
  "freq-we-usually-modal": "We can usually go together.",
  "freq-they-usually-gen": "They usually come late.",
  "freq-they-usually-be": "They are usually happy.",
  "freq-they-usually-modal": "They can usually win the game.",
  "freq-I-never-gen": "I never play soccer.",
  "freq-I-never-be": "I am never tired.",
  "freq-I-never-modal": "I can never help you.",
  "freq-she-never-gen": "She never goes there.",
  "freq-she-never-be": "She is never busy.",
  "freq-she-never-modal": "She can never come early.",
  "freq-he-never-gen": "He never eats breakfast.",
  "freq-he-never-be": "He is never late.",
  "freq-he-never-modal": "He can never remember it.",
  "freq-it-never-gen": "It never works well.",
  "freq-it-never-be": "It is never cold.",
  "freq-it-never-modal": "It can never start early.",
  "freq-we-never-gen": "We never meet here.",
  "freq-we-never-be": "We are never ready.",
  "freq-we-never-modal": "We can never go together.",
  "freq-they-never-gen": "They never come late.",
  "freq-they-never-be": "They are never happy.",
  "freq-they-never-modal": "They can never win the game.",
  "cmpadj-I-base-aff": "I am tall.",
  "cmpadj-she-base-aff": "She is smart.",
  "cmpadj-he-base-aff": "He is busy.",
  "cmpadj-it-base-aff": "It is interesting.",
  "cmpadj-we-base-aff": "We are happy.",
  "cmpadj-they-base-aff": "They are popular.",
  "cmpadj-I-equality-aff": "I am as tall as Mina.",
  "cmpadj-she-equality-aff": "She is as smart as Mina.",
  "cmpadj-he-equality-aff": "He is as busy as Jack.",
  "cmpadj-it-equality-aff": "It is as interesting as that book.",
  "cmpadj-we-equality-aff": "We are as happy as them.",
  "cmpadj-they-equality-aff": "They are as popular as us.",
  "cmpadj-I-comparative-aff": "I am taller than Mina.",
  "cmpadj-she-comparative-aff": "She is smarter than Mina.",
  "cmpadj-he-comparative-aff": "He is busier than Jack.",
  "cmpadj-it-comparative-aff": "It is more interesting than that book.",
  "cmpadj-we-comparative-aff": "We are happier than them.",
  "cmpadj-they-comparative-aff": "They are more popular than us.",
  "cmpadj-I-superlative-aff": "I am the tallest in my class.",
  "cmpadj-she-superlative-aff": "She is the smartest in her class.",
  "cmpadj-he-superlative-aff": "He is the busiest in his team.",
  "cmpadj-it-superlative-aff": "It is the most interesting of the three.",
  "cmpadj-we-superlative-aff": "We are the happiest in our school.",
  "cmpadj-they-superlative-aff": "They are the most popular in our school.",
  "cmpadv-I-base-aff": "I study hard.",
  "cmpadv-she-base-aff": "She works carefully.",
  "cmpadv-he-base-aff": "He runs fast.",
  "cmpadv-it-base-aff": "It moves quickly.",
  "cmpadv-we-base-aff": "We get up early.",
  "cmpadv-they-base-aff": "They talk loudly.",
  "cmpadv-I-equality-aff": "I study as hard as Mina.",
  "cmpadv-she-equality-aff": "She works as carefully as Mina.",
  "cmpadv-he-equality-aff": "He runs as fast as Jack.",
  "cmpadv-it-equality-aff": "It moves as quickly as that one.",
  "cmpadv-we-equality-aff": "We get up as early as them.",
  "cmpadv-they-equality-aff": "They talk as loudly as us.",
  "cmpadv-I-comparative-aff": "I study harder than Mina.",
  "cmpadv-she-comparative-aff": "She works more carefully than Mina.",
  "cmpadv-he-comparative-aff": "He runs faster than Jack.",
  "cmpadv-it-comparative-aff": "It moves more quickly than that one.",
  "cmpadv-we-comparative-aff": "We get up earlier than them.",
  "cmpadv-they-comparative-aff": "They talk more loudly than us.",
  "cmpadv-I-superlative-aff": "I study the hardest in my class.",
  "cmpadv-she-superlative-aff": "She works the most carefully in her team.",
  "cmpadv-he-superlative-aff": "He runs the fastest of the three.",
  "cmpadv-it-superlative-aff": "It moves the most quickly of the three.",
  "cmpadv-we-superlative-aff": "We get up the earliest in our class.",
  "cmpadv-they-superlative-aff": "They talk the most loudly in the group.",
  "adjpron-something-pos-np": "I want a cold drink.",
  "adjpron-something-pos-pron": "I want something cold.",
  "adjpron-somebody-pos-np": "I need a strong helper.",
  "adjpron-somebody-pos-pron": "I need somebody strong.",
  "adjpron-someone-pos-np": "She met a strange man.",
  "adjpron-someone-pos-pron": "She met someone strange.",
  "adjpron-anything-pos-np": "I don't want an expensive bag.",
  "adjpron-anything-pos-pron": "I don't want anything expensive.",
  "adjpron-nothing-pos-np": "There is no special reason.",
  "adjpron-nothing-pos-pron": "There is nothing special.",
  "adjpron-everything-pos-np": "I like every sweet food.",
  "adjpron-everything-pos-pron": "I like everything sweet.",
  "quantsome-books-there-aff": "There are some books.",
  "quantsome-books-there-neg": "There aren't any books.",
  "quantsome-books-there-q": "Are there any books?",
  "quantsome-water-there-aff": "There is some water.",
  "quantsome-water-there-neg": "There isn't any water.",
  "quantsome-water-there-q": "Is there any water?",
  "quantsome-students-there-aff": "There are some students.",
  "quantsome-students-there-neg": "There aren't any students.",
  "quantsome-students-there-q": "Are there any students?",
  "quantsome-money-there-aff": "There is some money.",
  "quantsome-money-there-neg": "There isn't any money.",
  "quantsome-money-there-q": "Is there any money?",
  "quantsome-questions-there-aff": "There are some questions.",
  "quantsome-questions-there-neg": "There aren't any questions.",
  "quantsome-questions-there-q": "Are there any questions?",
  "quantsome-time-there-aff": "There is some time.",
  "quantsome-time-there-neg": "There isn't any time.",
  "quantsome-time-there-q": "Is there any time?",
  "quantsome-books-have-aff": "I have some books.",
  "quantsome-books-have-neg": "I don't have any books.",
  "quantsome-books-have-q": "Do I have any books?",
  "quantsome-water-have-aff": "I have some water.",
  "quantsome-water-have-neg": "I don't have any water.",
  "quantsome-water-have-q": "Do I have any water?",
  "quantsome-students-have-aff": "I have some students.",
  "quantsome-students-have-neg": "I don't have any students.",
  "quantsome-students-have-q": "Do I have any students?",
  "quantsome-money-have-aff": "I have some money.",
  "quantsome-money-have-neg": "I don't have any money.",
  "quantsome-money-have-q": "Do I have any money?",
  "quantsome-questions-have-aff": "I have some questions.",
  "quantsome-questions-have-neg": "I don't have any questions.",
  "quantsome-questions-have-q": "Do I have any questions?",
  "quantsome-time-have-aff": "I have some time.",
  "quantsome-time-have-neg": "I don't have any time.",
  "quantsome-time-have-q": "Do I have any time?",
  "adv-I-adv-adj": "I am slow.",
  "adv-I-adv-advb": "I walk slowly.",
  "adv-she-adv-adj": "She is careful.",
  "adv-she-adv-advb": "She drives carefully.",
  "adv-he-adv-adj": "He is quick.",
  "adv-he-adv-advb": "He runs quickly.",
  "adv-it-adv-adj": "It is loud.",
  "adv-it-adv-advb": "It rings loudly.",
  "adv-we-adv-adj": "We are quiet.",
  "adv-we-adv-advb": "We speak quietly.",
  "adv-they-adv-adj": "They are kind.",
  "adv-they-adv-advb": "They smile kindly.",
  "warmup-tall-base-word": "tall",
  "warmup-nice-base-word": "nice",
  "warmup-happy-base-word": "happy",
  "warmup-big-base-word": "big",
  "warmup-beautiful-base-word": "beautiful",
  "warmup-good-base-word": "good",
  "warmup-bad-base-word": "bad",
  "warmup-many-base-word": "many / much",
  "warmup-little-base-word": "little",
  "warmup-tall-comparative-word": "taller",
  "warmup-nice-comparative-word": "nicer",
  "warmup-happy-comparative-word": "happier",
  "warmup-big-comparative-word": "bigger",
  "warmup-beautiful-comparative-word": "more beautiful",
  "warmup-good-comparative-word": "better",
  "warmup-bad-comparative-word": "worse",
  "warmup-many-comparative-word": "more",
  "warmup-little-comparative-word": "less",
  "warmup-tall-superlative-word": "tallest",
  "warmup-nice-superlative-word": "nicest",
  "warmup-happy-superlative-word": "happiest",
  "warmup-big-superlative-word": "biggest",
  "warmup-beautiful-superlative-word": "most beautiful",
  "warmup-good-superlative-word": "best",
  "warmup-bad-superlative-word": "worst",
  "warmup-many-superlative-word": "most",
  "warmup-little-superlative-word": "least"
};
export const KO = {
  "be-I-present-aff": "나는 늦는다",
  "be-I-present-neg": "나는 늦지 않는다",
  "be-I-present-q": "나는 늦니?",
  "be-she-present-aff": "그녀는 아름답다",
  "be-she-present-neg": "그녀는 아름답지 않다",
  "be-she-present-q": "그녀는 아름답니?",
  "be-he-present-aff": "그는 바쁘다",
  "be-he-present-neg": "그는 바쁘지 않다",
  "be-he-present-q": "그는 바쁘니?",
  "be-it-present-aff": "날씨가 춥다",
  "be-it-present-neg": "날씨가 춥지 않다",
  "be-it-present-q": "날씨가 춥니?",
  "be-we-present-aff": "우리는 준비됐다",
  "be-we-present-neg": "우리는 준비되지 않았다",
  "be-we-present-q": "우리는 준비됐니?",
  "be-they-present-aff": "그들은 여기 있다",
  "be-they-present-neg": "그들은 여기 없다",
  "be-they-present-q": "그들은 여기 있니?",
  "be-I-past-aff": "나는 늦었다",
  "be-I-past-neg": "나는 늦지 않았다",
  "be-I-past-q": "나는 늦었니?",
  "be-she-past-aff": "그녀는 아름다웠다",
  "be-she-past-neg": "그녀는 아름답지 않았다",
  "be-she-past-q": "그녀는 아름다웠니?",
  "be-he-past-aff": "그는 바빴다",
  "be-he-past-neg": "그는 바쁘지 않았다",
  "be-he-past-q": "그는 바빴니?",
  "be-it-past-aff": "날씨가 추웠다",
  "be-it-past-neg": "날씨가 춥지 않았다",
  "be-it-past-q": "날씨가 추웠니?",
  "be-we-past-aff": "우리는 준비돼 있었다",
  "be-we-past-neg": "우리는 준비돼 있지 않았다",
  "be-we-past-q": "우리는 준비돼 있었니?",
  "be-they-past-aff": "그들은 여기 있었다",
  "be-they-past-neg": "그들은 여기 없었다",
  "be-they-past-q": "그들은 여기 있었니?",
  "be-I-will-aff": "나는 늦을 것이다",
  "be-I-will-neg": "나는 늦지 않을 것이다",
  "be-I-will-q": "내가 늦을까?",
  "be-she-will-aff": "그녀는 괜찮을 것이다",
  "be-she-will-neg": "그녀는 괜찮지 않을 것이다",
  "be-she-will-q": "그녀가 괜찮을까?",
  "be-he-will-aff": "그는 바쁠 것이다",
  "be-he-will-neg": "그는 바쁘지 않을 것이다",
  "be-he-will-q": "그가 바쁠까?",
  "be-it-will-aff": "날씨가 추울 것이다",
  "be-it-will-neg": "날씨가 춥지 않을 것이다",
  "be-it-will-q": "날씨가 추울까?",
  "be-we-will-aff": "우리는 준비될 것이다",
  "be-we-will-neg": "우리는 준비되지 않을 것이다",
  "be-we-will-q": "우리가 준비될까?",
  "be-they-will-aff": "그들은 여기 있을 것이다",
  "be-they-will-neg": "그들은 여기 없을 것이다",
  "be-they-will-q": "그들이 여기 있을까?",
  "be-I-goingto-aff": "나는 늦을 예정이다",
  "be-I-goingto-neg": "나는 늦지 않을 예정이다",
  "be-I-goingto-q": "나는 늦을 예정이니?",
  "be-she-goingto-aff": "그녀는 괜찮아질 것이다",
  "be-she-goingto-neg": "그녀는 괜찮아지지 않을 것이다",
  "be-she-goingto-q": "그녀가 괜찮아질까?",
  "be-he-goingto-aff": "그는 바쁠 예정이다",
  "be-he-goingto-neg": "그는 바쁘지 않을 예정이다",
  "be-he-goingto-q": "그는 바쁠 예정이니?",
  "be-it-goingto-aff": "날씨가 추워질 것이다",
  "be-it-goingto-neg": "날씨가 추워지지 않을 것이다",
  "be-it-goingto-q": "날씨가 추워질까?",
  "be-we-goingto-aff": "우리는 준비될 예정이다",
  "be-we-goingto-neg": "우리는 준비되지 않을 예정이다",
  "be-we-goingto-q": "우리는 준비될 예정이니?",
  "be-they-goingto-aff": "그들은 여기 있을 예정이다",
  "be-they-goingto-neg": "그들은 여기 없을 예정이다",
  "be-they-goingto-q": "그들은 여기 있을 예정이니?",
  "verb-I-present-aff": "나는 너를 안다",
  "verb-I-present-neg": "나는 너를 모른다",
  "verb-I-present-q": "내가 너를 아니?",
  "verb-she-present-aff": "그녀는 그것을 좋아한다",
  "verb-she-present-neg": "그녀는 그것을 좋아하지 않는다",
  "verb-she-present-q": "그녀가 그것을 좋아하니?",
  "verb-he-present-aff": "그는 그것을 안다",
  "verb-he-present-neg": "그는 그것을 모른다",
  "verb-he-present-q": "그가 그것을 아니?",
  "verb-it-present-aff": "그것은 작동한다",
  "verb-it-present-neg": "그것은 작동하지 않는다",
  "verb-it-present-q": "그것이 작동하니?",
  "verb-we-present-aff": "우리는 그것이 필요하다",
  "verb-we-present-neg": "우리는 그것이 필요하지 않다",
  "verb-we-present-q": "우리가 그것이 필요하니?",
  "verb-they-present-aff": "그들은 그것을 좋아한다",
  "verb-they-present-neg": "그들은 그것을 좋아하지 않는다",
  "verb-they-present-q": "그들이 그것을 좋아하니?",
  "verb-I-past-aff": "나는 너를 알았다",
  "verb-I-past-neg": "나는 너를 몰랐다",
  "verb-I-past-q": "내가 너를 알았니?",
  "verb-she-past-aff": "그녀는 그것을 좋아했다",
  "verb-she-past-neg": "그녀는 그것을 좋아하지 않았다",
  "verb-she-past-q": "그녀가 그것을 좋아했니?",
  "verb-he-past-aff": "그는 그것을 알았다",
  "verb-he-past-neg": "그는 그것을 몰랐다",
  "verb-he-past-q": "그가 그것을 알았니?",
  "verb-it-past-aff": "그것은 작동했다",
  "verb-it-past-neg": "그것은 작동하지 않았다",
  "verb-it-past-q": "그것이 작동했니?",
  "verb-we-past-aff": "우리는 그것이 필요했다",
  "verb-we-past-neg": "우리는 그것이 필요하지 않았다",
  "verb-we-past-q": "우리가 그것이 필요했니?",
  "verb-they-past-aff": "그들은 그것을 좋아했다",
  "verb-they-past-neg": "그들은 그것을 좋아하지 않았다",
  "verb-they-past-q": "그들이 그것을 좋아했니?",
  "verb-I-will-aff": "나는 너를 만날 것이다",
  "verb-I-will-neg": "나는 너를 만나지 않을 것이다",
  "verb-I-will-q": "내가 너를 만날까?",
  "verb-she-will-aff": "그녀는 그것을 좋아할 것이다",
  "verb-she-will-neg": "그녀는 그것을 좋아하지 않을 것이다",
  "verb-she-will-q": "그녀가 그것을 좋아할까?",
  "verb-he-will-aff": "그는 올 것이다",
  "verb-he-will-neg": "그는 오지 않을 것이다",
  "verb-he-will-q": "그가 올까?",
  "verb-it-will-aff": "그것은 작동할 것이다",
  "verb-it-will-neg": "그것은 작동하지 않을 것이다",
  "verb-it-will-q": "그것이 작동할까?",
  "verb-we-will-aff": "우리는 그것이 필요할 것이다",
  "verb-we-will-neg": "우리는 그것이 필요하지 않을 것이다",
  "verb-we-will-q": "우리가 그것이 필요할까?",
  "verb-they-will-aff": "그들은 그것을 좋아할 것이다",
  "verb-they-will-neg": "그들은 그것을 좋아하지 않을 것이다",
  "verb-they-will-q": "그들이 그것을 좋아할까?",
  "verb-I-goingto-aff": "나는 너를 만날 예정이다",
  "verb-I-goingto-neg": "나는 너를 만나지 않을 예정이다",
  "verb-I-goingto-q": "나는 너를 만날 예정이니?",
  "verb-she-goingto-aff": "그녀는 그것을 좋아하게 될 것이다",
  "verb-she-goingto-neg": "그녀는 그것을 좋아하게 되지는 않을 것이다",
  "verb-she-goingto-q": "그녀가 그것을 좋아하게 될까?",
  "verb-he-goingto-aff": "그는 올 예정이다",
  "verb-he-goingto-neg": "그는 오지 않을 예정이다",
  "verb-he-goingto-q": "그는 올 예정이니?",
  "verb-it-goingto-aff": "그것은 작동하게 될 것이다",
  "verb-it-goingto-neg": "그것은 작동하지 않게 될 것이다",
  "verb-it-goingto-q": "그것이 작동하게 될까?",
  "verb-we-goingto-aff": "우리는 그것이 필요해질 것이다",
  "verb-we-goingto-neg": "우리는 그것이 필요해지지 않을 것이다",
  "verb-we-goingto-q": "우리가 그것이 필요해질까?",
  "verb-they-goingto-aff": "그들은 그것을 좋아하게 될 것이다",
  "verb-they-goingto-neg": "그들은 그것을 좋아하게 되지는 않을 것이다",
  "verb-they-goingto-q": "그들이 그것을 좋아하게 될까?",
  "prog-I-present-aff": "나는 일하고 있다",
  "prog-I-present-neg": "나는 일하고 있지 않다",
  "prog-I-present-q": "내가 일하고 있니?",
  "prog-she-present-aff": "그녀는 오고 있다",
  "prog-she-present-neg": "그녀는 오고 있지 않다",
  "prog-she-present-q": "그녀가 오고 있니?",
  "prog-he-present-aff": "그는 기다리고 있다",
  "prog-he-present-neg": "그는 기다리고 있지 않다",
  "prog-he-present-q": "그가 기다리고 있니?",
  "prog-it-present-aff": "비가 오고 있다",
  "prog-it-present-neg": "비가 오고 있지 않다",
  "prog-it-present-q": "비가 오고 있니?",
  "prog-we-present-aff": "우리는 기다리고 있다",
  "prog-we-present-neg": "우리는 기다리고 있지 않다",
  "prog-we-present-q": "우리가 기다리고 있니?",
  "prog-they-present-aff": "그들은 오고 있다",
  "prog-they-present-neg": "그들은 오고 있지 않다",
  "prog-they-present-q": "그들이 오고 있니?",
  "prog-I-past-aff": "나는 일하고 있었다",
  "prog-I-past-neg": "나는 일하고 있지 않았다",
  "prog-I-past-q": "내가 일하고 있었니?",
  "prog-she-past-aff": "그녀는 오고 있었다",
  "prog-she-past-neg": "그녀는 오고 있지 않았다",
  "prog-she-past-q": "그녀가 오고 있었니?",
  "prog-he-past-aff": "그는 기다리고 있었다",
  "prog-he-past-neg": "그는 기다리고 있지 않았다",
  "prog-he-past-q": "그가 기다리고 있었니?",
  "prog-it-past-aff": "비가 오고 있었다",
  "prog-it-past-neg": "비가 오고 있지 않았다",
  "prog-it-past-q": "비가 오고 있었니?",
  "prog-we-past-aff": "우리는 기다리고 있었다",
  "prog-we-past-neg": "우리는 기다리고 있지 않았다",
  "prog-we-past-q": "우리가 기다리고 있었니?",
  "prog-they-past-aff": "그들은 오고 있었다",
  "prog-they-past-neg": "그들은 오고 있지 않았다",
  "prog-they-past-q": "그들이 오고 있었니?",
  "pass-I-present-aff": "나는 초대받는다",
  "pass-I-present-neg": "나는 초대받지 않는다",
  "pass-I-present-q": "내가 초대받니?",
  "pass-she-present-aff": "그녀는 초대받는다",
  "pass-she-present-neg": "그녀는 초대받지 않는다",
  "pass-she-present-q": "그녀가 초대받니?",
  "pass-he-present-aff": "그는 초대받는다",
  "pass-he-present-neg": "그는 초대받지 않는다",
  "pass-he-present-q": "그가 초대받니?",
  "pass-it-present-aff": "그것은 고장 나 있다",
  "pass-it-present-neg": "그것은 고장 나 있지 않다",
  "pass-it-present-q": "그것이 고장 나 있니?",
  "pass-we-present-aff": "우리는 초대받는다",
  "pass-we-present-neg": "우리는 초대받지 않는다",
  "pass-we-present-q": "우리가 초대받니?",
  "pass-they-present-aff": "그들은 초대받는다",
  "pass-they-present-neg": "그들은 초대받지 않는다",
  "pass-they-present-q": "그들이 초대받니?",
  "pass-I-past-aff": "나는 초대받았다",
  "pass-I-past-neg": "나는 초대받지 않았다",
  "pass-I-past-q": "내가 초대받았니?",
  "pass-she-past-aff": "그녀는 초대받았다",
  "pass-she-past-neg": "그녀는 초대받지 않았다",
  "pass-she-past-q": "그녀가 초대받았니?",
  "pass-he-past-aff": "그는 초대받았다",
  "pass-he-past-neg": "그는 초대받지 않았다",
  "pass-he-past-q": "그가 초대받았니?",
  "pass-it-past-aff": "그것은 고장 나 있었다",
  "pass-it-past-neg": "그것은 고장 나 있지 않았다",
  "pass-it-past-q": "그것이 고장 나 있었니?",
  "pass-we-past-aff": "우리는 초대받았다",
  "pass-we-past-neg": "우리는 초대받지 않았다",
  "pass-we-past-q": "우리가 초대받았니?",
  "pass-they-past-aff": "그들은 초대받았다",
  "pass-they-past-neg": "그들은 초대받지 않았다",
  "pass-they-past-q": "그들이 초대받았니?",
  "passget-I-present-aff": "나는 초대를 받는다",
  "passget-I-present-neg": "나는 초대를 받지 않는다",
  "passget-I-present-q": "내가 초대를 받니?",
  "passget-she-present-aff": "그녀는 초대를 받는다",
  "passget-she-present-neg": "그녀는 초대를 받지 않는다",
  "passget-she-present-q": "그녀가 초대를 받니?",
  "passget-he-present-aff": "그는 초대를 받는다",
  "passget-he-present-neg": "그는 초대를 받지 않는다",
  "passget-he-present-q": "그가 초대를 받니?",
  "passget-it-present-aff": "그것은 고장이 난다",
  "passget-it-present-neg": "그것은 고장이 나지 않는다",
  "passget-it-present-q": "그것이 고장이 나니?",
  "passget-we-present-aff": "우리는 초대를 받는다",
  "passget-we-present-neg": "우리는 초대를 받지 않는다",
  "passget-we-present-q": "우리가 초대를 받니?",
  "passget-they-present-aff": "그들은 초대를 받는다",
  "passget-they-present-neg": "그들은 초대를 받지 않는다",
  "passget-they-present-q": "그들이 초대를 받니?",
  "passget-I-past-aff": "나는 초대를 받았다",
  "passget-I-past-neg": "나는 초대를 받지 못했다",
  "passget-I-past-q": "내가 초대를 받았니?",
  "passget-she-past-aff": "그녀는 초대를 받았다",
  "passget-she-past-neg": "그녀는 초대를 받지 못했다",
  "passget-she-past-q": "그녀가 초대를 받았니?",
  "passget-he-past-aff": "그는 초대를 받았다",
  "passget-he-past-neg": "그는 초대를 받지 못했다",
  "passget-he-past-q": "그가 초대를 받았니?",
  "passget-it-past-aff": "그것은 고장이 났다",
  "passget-it-past-neg": "그것은 고장이 나지 않았다",
  "passget-it-past-q": "그것이 고장이 났니?",
  "passget-we-past-aff": "우리는 초대를 받았다",
  "passget-we-past-neg": "우리는 초대를 받지 못했다",
  "passget-we-past-q": "우리가 초대를 받았니?",
  "passget-they-past-aff": "그들은 초대를 받았다",
  "passget-they-past-neg": "그들은 초대를 받지 못했다",
  "passget-they-past-q": "그들이 초대를 받았니?",
  "keep-I-present-aff": "나는 계속 일한다",
  "keep-I-present-neg": "나는 계속 일하지는 않는다",
  "keep-I-present-q": "내가 계속 일하니?",
  "keep-she-present-aff": "그녀는 계속 온다",
  "keep-she-present-neg": "그녀는 계속 오지는 않는다",
  "keep-she-present-q": "그녀가 계속 오니?",
  "keep-he-present-aff": "그는 계속 기다린다",
  "keep-he-present-neg": "그는 계속 기다리지는 않는다",
  "keep-he-present-q": "그가 계속 기다리니?",
  "keep-it-present-aff": "비가 계속 온다",
  "keep-it-present-neg": "비가 계속 오지는 않는다",
  "keep-it-present-q": "비가 계속 오니?",
  "keep-we-present-aff": "우리는 계속 기다린다",
  "keep-we-present-neg": "우리는 계속 기다리지는 않는다",
  "keep-we-present-q": "우리가 계속 기다리니?",
  "keep-they-present-aff": "그들은 계속 온다",
  "keep-they-present-neg": "그들은 계속 오지는 않는다",
  "keep-they-present-q": "그들이 계속 오니?",
  "keep-I-past-aff": "나는 계속 일했다",
  "keep-I-past-neg": "나는 계속 일하지는 않았다",
  "keep-I-past-q": "내가 계속 일했니?",
  "keep-she-past-aff": "그녀는 계속 왔다",
  "keep-she-past-neg": "그녀는 계속 오지는 않았다",
  "keep-she-past-q": "그녀가 계속 왔니?",
  "keep-he-past-aff": "그는 계속 기다렸다",
  "keep-he-past-neg": "그는 계속 기다리지는 않았다",
  "keep-he-past-q": "그가 계속 기다렸니?",
  "keep-it-past-aff": "비가 계속 왔다",
  "keep-it-past-neg": "비가 계속 오지는 않았다",
  "keep-it-past-q": "비가 계속 왔니?",
  "keep-we-past-aff": "우리는 계속 기다렸다",
  "keep-we-past-neg": "우리는 계속 기다리지는 않았다",
  "keep-we-past-q": "우리가 계속 기다렸니?",
  "keep-they-past-aff": "그들은 계속 왔다",
  "keep-they-past-neg": "그들은 계속 오지는 않았다",
  "keep-they-past-q": "그들이 계속 왔니?",
  "perfbe-I-perf-aff": "나는 계속 바빴다",
  "perfbe-I-perf-neg": "나는 계속 바쁘지는 않았다",
  "perfbe-I-perf-q": "내가 계속 바빴니?",
  "perfbe-she-perf-aff": "그녀는 계속 바빴다",
  "perfbe-she-perf-neg": "그녀는 계속 바쁘지는 않았다",
  "perfbe-she-perf-q": "그녀가 계속 바빴니?",
  "perfbe-he-perf-aff": "그는 계속 바빴다",
  "perfbe-he-perf-neg": "그는 계속 바쁘지는 않았다",
  "perfbe-he-perf-q": "그가 계속 바빴니?",
  "perfbe-it-perf-aff": "날씨가 계속 추웠다",
  "perfbe-it-perf-neg": "날씨가 계속 춥지는 않았다",
  "perfbe-it-perf-q": "날씨가 계속 추웠니?",
  "perfbe-we-perf-aff": "우리는 계속 바빴다",
  "perfbe-we-perf-neg": "우리는 계속 바쁘지는 않았다",
  "perfbe-we-perf-q": "우리가 계속 바빴니?",
  "perfbe-they-perf-aff": "그들은 계속 여기 있었다",
  "perfbe-they-perf-neg": "그들은 계속 여기 있지는 않았다",
  "perfbe-they-perf-q": "그들이 계속 여기 있었니?",
  "perfverb-I-perf-aff": "나는 그것을 본 적 있다",
  "perfverb-I-perf-neg": "나는 그것을 본 적 없다",
  "perfverb-I-perf-q": "내가 그것을 본 적 있니?",
  "perfverb-she-perf-aff": "그녀는 그것을 본 적 있다",
  "perfverb-she-perf-neg": "그녀는 그것을 본 적 없다",
  "perfverb-she-perf-q": "그녀가 그것을 본 적 있니?",
  "perfverb-he-perf-aff": "그는 그것을 본 적 있다",
  "perfverb-he-perf-neg": "그는 그것을 본 적 없다",
  "perfverb-he-perf-q": "그가 그것을 본 적 있니?",
  "perfverb-it-perf-aff": "그것은 잘 작동해 왔다",
  "perfverb-it-perf-neg": "그것은 잘 작동해 오지 않았다",
  "perfverb-it-perf-q": "그것이 잘 작동해 왔니?",
  "perfverb-we-perf-aff": "우리는 그것을 본 적 있다",
  "perfverb-we-perf-neg": "우리는 그것을 본 적 없다",
  "perfverb-we-perf-q": "우리가 그것을 본 적 있니?",
  "perfverb-they-perf-aff": "그들은 그것을 본 적 있다",
  "perfverb-they-perf-neg": "그들은 그것을 본 적 없다",
  "perfverb-they-perf-q": "그들이 그것을 본 적 있니?",
  "can-I-modal-aff": "나는 그것을 할 수 있다",
  "can-I-modal-neg": "나는 그것을 할 수 없다",
  "can-I-modal-q": "내가 그것을 할 수 있을까?",
  "can-she-modal-aff": "그녀는 올 수 있다",
  "can-she-modal-neg": "그녀는 올 수 없다",
  "can-she-modal-q": "그녀가 올 수 있니?",
  "can-he-modal-aff": "그는 도울 수 있다",
  "can-he-modal-neg": "그는 도울 수 없다",
  "can-he-modal-q": "그가 도울 수 있니?",
  "can-it-modal-aff": "그것은 미뤄도 된다",
  "can-it-modal-neg": "그것은 미룰 수 없다",
  "can-it-modal-q": "그것은 미뤄도 되니?",
  "can-we-modal-aff": "우리는 갈 수 있다",
  "can-we-modal-neg": "우리는 갈 수 없다",
  "can-we-modal-q": "우리가 가도 되니?",
  "can-they-modal-aff": "그들은 도울 수 있다",
  "can-they-modal-neg": "그들은 도울 수 없다",
  "can-they-modal-q": "그들이 도울 수 있니?",
  "should-I-modal-aff": "나는 가야 한다",
  "should-I-modal-neg": "나는 가지 말아야 한다",
  "should-I-modal-q": "내가 가야 할까?",
  "should-she-modal-aff": "그녀는 와야 한다",
  "should-she-modal-neg": "그녀는 오지 말아야 한다",
  "should-she-modal-q": "그녀가 와야 할까?",
  "should-he-modal-aff": "그는 기다려야 한다",
  "should-he-modal-neg": "그는 기다리지 말아야 한다",
  "should-he-modal-q": "그가 기다려야 할까?",
  "should-it-modal-aff": "그것은 준비돼 있어야 한다",
  "should-it-modal-neg": "그것은 준비돼 있지 않아야 한다",
  "should-it-modal-q": "그것이 준비돼 있어야 할까?",
  "should-we-modal-aff": "우리는 가야 한다",
  "should-we-modal-neg": "우리는 가지 말아야 한다",
  "should-we-modal-q": "우리가 가야 할까?",
  "should-they-modal-aff": "그들은 와야 한다",
  "should-they-modal-neg": "그들은 오지 말아야 한다",
  "should-they-modal-q": "그들이 와야 할까?",
  "whbe-I-wh-where": "나는 어디에 있니?",
  "whbe-I-wh-when": "나는 언제 한가하니?",
  "whbe-I-wh-why": "나는 왜 여기에 있니?",
  "whbe-she-wh-where": "그녀는 어디에 있니?",
  "whbe-she-wh-when": "그녀는 언제 오니?",
  "whbe-she-wh-why": "그녀는 왜 늦었니?",
  "whbe-he-wh-where": "그는 어디에 있니?",
  "whbe-he-wh-when": "그는 언제 오니?",
  "whbe-he-wh-why": "그는 왜 화가 났니?",
  "whbe-it-wh-where": "그것은 어디에 있니?",
  "whbe-it-wh-when": "그것은 언제니?",
  "whbe-it-wh-why": "날씨가 왜 춥니?",
  "whbe-we-wh-where": "우리는 어디에 있니?",
  "whbe-we-wh-when": "우리는 언제 떠나니?",
  "whbe-we-wh-why": "우리는 왜 여기에 있니?",
  "whbe-they-wh-where": "그들은 어디에 있니?",
  "whbe-they-wh-when": "그들은 언제 오니?",
  "whbe-they-wh-why": "그들은 왜 여기에 있니?",
  "whdo-I-wh-what": "나는 무엇을 해야 하니?",
  "whdo-I-wh-how": "내가 어떻게 아니?",
  "whdo-I-wh-why": "나는 왜 그것이 필요하니?",
  "whdo-she-wh-what": "그녀는 무엇을 원하니?",
  "whdo-she-wh-how": "그녀는 어떻게 아니?",
  "whdo-she-wh-why": "그녀는 왜 그것을 좋아하니?",
  "whdo-he-wh-what": "그는 무엇을 원하니?",
  "whdo-he-wh-how": "그는 그것을 어떻게 하니?",
  "whdo-he-wh-why": "그는 왜 그것이 필요하니?",
  "whdo-it-wh-what": "그것은 무슨 뜻이니?",
  "whdo-it-wh-how": "그것은 어떻게 작동하니?",
  "whdo-it-wh-why": "그것이 왜 중요하니?",
  "whdo-we-wh-what": "우리는 무엇이 필요하니?",
  "whdo-we-wh-how": "우리는 거기에 어떻게 가니?",
  "whdo-we-wh-why": "우리는 왜 그것이 필요하니?",
  "whdo-they-wh-what": "그들은 무엇을 원하니?",
  "whdo-they-wh-how": "그들은 어떻게 아니?",
  "whdo-they-wh-why": "그들은 왜 그것을 좋아하니?",
  "adjpos-I-pos-comp": "나는 바쁘다",
  "adjpos-I-pos-attr": "나는 바쁜 학생이다",
  "adjpos-she-pos-comp": "그녀는 친절하다",
  "adjpos-she-pos-attr": "그녀는 친절한 소녀다",
  "adjpos-he-pos-comp": "그는 키가 크다",
  "adjpos-he-pos-attr": "그는 키 큰 소년이다",
  "adjpos-it-pos-comp": "그것은 작다",
  "adjpos-it-pos-attr": "그것은 작은 사과다",
  "adjpos-we-pos-comp": "우리는 어리다",
  "adjpos-we-pos-attr": "우리는 어린 학생들이다",
  "adjpos-they-pos-comp": "그들은 유명하다",
  "adjpos-they-pos-attr": "그들은 유명한 가수들이다",
  "quant-I-many-cnt": "나는 책이 많다",
  "quant-I-many-unc": "나는 시간이 많다",
  "quant-she-many-cnt": "그녀는 친구가 많다",
  "quant-she-many-unc": "그녀는 돈이 많다",
  "quant-he-many-cnt": "그는 펜이 많다",
  "quant-he-many-unc": "그는 빵이 많다",
  "quant-it-many-cnt": "그것은 색깔이 많다",
  "quant-it-many-unc": "그것은 공간이 많다",
  "quant-we-many-cnt": "우리는 의자가 많다",
  "quant-we-many-unc": "우리는 일이 많다",
  "quant-they-many-cnt": "그들은 질문이 많다",
  "quant-they-many-unc": "그들은 숙제가 많다",
  "quant-I-afew-cnt": "나는 책이 조금 있다",
  "quant-I-afew-unc": "나는 시간이 조금 있다",
  "quant-she-afew-cnt": "그녀는 친구가 조금 있다",
  "quant-she-afew-unc": "그녀는 돈이 조금 있다",
  "quant-he-afew-cnt": "그는 펜이 조금 있다",
  "quant-he-afew-unc": "그는 빵이 조금 있다",
  "quant-it-afew-cnt": "그것은 색깔이 조금 있다",
  "quant-it-afew-unc": "그것은 공간이 조금 있다",
  "quant-we-afew-cnt": "우리는 의자가 조금 있다",
  "quant-we-afew-unc": "우리는 일이 조금 있다",
  "quant-they-afew-cnt": "그들은 질문이 조금 있다",
  "quant-they-afew-unc": "그들은 숙제가 조금 있다",
  "quant-I-few-cnt": "나는 책이 거의 없다",
  "quant-I-few-unc": "나는 시간이 거의 없다",
  "quant-she-few-cnt": "그녀는 친구가 거의 없다",
  "quant-she-few-unc": "그녀는 돈이 거의 없다",
  "quant-he-few-cnt": "그는 펜이 거의 없다",
  "quant-he-few-unc": "그는 빵이 거의 없다",
  "quant-it-few-cnt": "그것은 색깔이 거의 없다",
  "quant-it-few-unc": "그것은 공간이 거의 없다",
  "quant-we-few-cnt": "우리는 의자가 거의 없다",
  "quant-we-few-unc": "우리는 일이 거의 없다",
  "quant-they-few-cnt": "그들은 질문이 거의 없다",
  "quant-they-few-unc": "그들은 숙제가 거의 없다",
  "freq-I-often-gen": "나는 자주 축구를 한다",
  "freq-I-often-be": "나는 자주 피곤하다",
  "freq-I-often-modal": "나는 자주 너를 도울 수 있다",
  "freq-she-often-gen": "그녀는 자주 거기에 간다",
  "freq-she-often-be": "그녀는 자주 바쁘다",
  "freq-she-often-modal": "그녀는 자주 일찍 올 수 있다",
  "freq-he-often-gen": "그는 자주 아침을 먹는다",
  "freq-he-often-be": "그는 자주 늦는다",
  "freq-he-often-modal": "그는 자주 그것을 기억할 수 있다",
  "freq-it-often-gen": "그것은 자주 잘 작동한다",
  "freq-it-often-be": "날씨가 자주 춥다",
  "freq-it-often-modal": "그것은 자주 일찍 시작할 수 있다",
  "freq-we-often-gen": "우리는 자주 여기서 만난다",
  "freq-we-often-be": "우리는 자주 준비돼 있다",
  "freq-we-often-modal": "우리는 자주 함께 갈 수 있다",
  "freq-they-often-gen": "그들은 자주 늦게 온다",
  "freq-they-often-be": "그들은 자주 행복하다",
  "freq-they-often-modal": "그들은 자주 경기를 이길 수 있다",
  "freq-I-usually-gen": "나는 보통 축구를 한다",
  "freq-I-usually-be": "나는 보통 피곤하다",
  "freq-I-usually-modal": "나는 보통 너를 도울 수 있다",
  "freq-she-usually-gen": "그녀는 보통 거기에 간다",
  "freq-she-usually-be": "그녀는 보통 바쁘다",
  "freq-she-usually-modal": "그녀는 보통 일찍 올 수 있다",
  "freq-he-usually-gen": "그는 보통 아침을 먹는다",
  "freq-he-usually-be": "그는 보통 늦는다",
  "freq-he-usually-modal": "그는 보통 그것을 기억할 수 있다",
  "freq-it-usually-gen": "그것은 보통 잘 작동한다",
  "freq-it-usually-be": "날씨가 보통 춥다",
  "freq-it-usually-modal": "그것은 보통 일찍 시작할 수 있다",
  "freq-we-usually-gen": "우리는 보통 여기서 만난다",
  "freq-we-usually-be": "우리는 보통 준비돼 있다",
  "freq-we-usually-modal": "우리는 보통 함께 갈 수 있다",
  "freq-they-usually-gen": "그들은 보통 늦게 온다",
  "freq-they-usually-be": "그들은 보통 행복하다",
  "freq-they-usually-modal": "그들은 보통 경기를 이길 수 있다",
  "freq-I-never-gen": "나는 축구를 절대 하지 않는다",
  "freq-I-never-be": "나는 절대 피곤하지 않다",
  "freq-I-never-modal": "나는 너를 절대 도울 수 없다",
  "freq-she-never-gen": "그녀는 거기에 절대 가지 않는다",
  "freq-she-never-be": "그녀는 절대 바쁘지 않다",
  "freq-she-never-modal": "그녀는 절대 일찍 올 수 없다",
  "freq-he-never-gen": "그는 아침을 절대 먹지 않는다",
  "freq-he-never-be": "그는 절대 늦지 않는다",
  "freq-he-never-modal": "그는 그것을 절대 기억할 수 없다",
  "freq-it-never-gen": "그것은 절대 잘 작동하지 않는다",
  "freq-it-never-be": "날씨가 절대 춥지 않다",
  "freq-it-never-modal": "그것은 절대 일찍 시작할 수 없다",
  "freq-we-never-gen": "우리는 여기서 절대 만나지 않는다",
  "freq-we-never-be": "우리는 절대 준비돼 있지 않다",
  "freq-we-never-modal": "우리는 절대 함께 갈 수 없다",
  "freq-they-never-gen": "그들은 절대 늦게 오지 않는다",
  "freq-they-never-be": "그들은 절대 행복하지 않다",
  "freq-they-never-modal": "그들은 절대 경기를 이길 수 없다",
  "cmpadj-I-base-aff": "나는 키가 크다",
  "cmpadj-she-base-aff": "그녀는 똑똑하다",
  "cmpadj-he-base-aff": "그는 바쁘다",
  "cmpadj-it-base-aff": "그것은 재미있다",
  "cmpadj-we-base-aff": "우리는 행복하다",
  "cmpadj-they-base-aff": "그들은 인기가 있다",
  "cmpadj-I-equality-aff": "나는 미나만큼 키가 크다",
  "cmpadj-she-equality-aff": "그녀는 미나만큼 똑똑하다",
  "cmpadj-he-equality-aff": "그는 잭만큼 바쁘다",
  "cmpadj-it-equality-aff": "그것은 그 책만큼 재미있다",
  "cmpadj-we-equality-aff": "우리는 그들만큼 행복하다",
  "cmpadj-they-equality-aff": "그들은 우리만큼 인기가 있다",
  "cmpadj-I-comparative-aff": "나는 미나보다 키가 크다",
  "cmpadj-she-comparative-aff": "그녀는 미나보다 똑똑하다",
  "cmpadj-he-comparative-aff": "그는 잭보다 바쁘다",
  "cmpadj-it-comparative-aff": "그것은 그 책보다 재미있다",
  "cmpadj-we-comparative-aff": "우리는 그들보다 행복하다",
  "cmpadj-they-comparative-aff": "그들은 우리보다 인기가 있다",
  "cmpadj-I-superlative-aff": "나는 우리 반에서 키가 가장 크다",
  "cmpadj-she-superlative-aff": "그녀는 반에서 가장 똑똑하다",
  "cmpadj-he-superlative-aff": "그는 팀에서 가장 바쁘다",
  "cmpadj-it-superlative-aff": "그것은 셋 중에서 가장 재미있다",
  "cmpadj-we-superlative-aff": "우리는 학교에서 가장 행복하다",
  "cmpadj-they-superlative-aff": "그들은 학교에서 가장 인기가 있다",
  "cmpadv-I-base-aff": "나는 열심히 공부한다",
  "cmpadv-she-base-aff": "그녀는 신중하게 일한다",
  "cmpadv-he-base-aff": "그는 빠르게 달린다",
  "cmpadv-it-base-aff": "그것은 빠르게 움직인다",
  "cmpadv-we-base-aff": "우리는 일찍 일어난다",
  "cmpadv-they-base-aff": "그들은 크게 말한다",
  "cmpadv-I-equality-aff": "나는 미나만큼 열심히 공부한다",
  "cmpadv-she-equality-aff": "그녀는 미나만큼 신중하게 일한다",
  "cmpadv-he-equality-aff": "그는 잭만큼 빠르게 달린다",
  "cmpadv-it-equality-aff": "그것은 저것만큼 빠르게 움직인다",
  "cmpadv-we-equality-aff": "우리는 그들만큼 일찍 일어난다",
  "cmpadv-they-equality-aff": "그들은 우리만큼 크게 말한다",
  "cmpadv-I-comparative-aff": "나는 미나보다 열심히 공부한다",
  "cmpadv-she-comparative-aff": "그녀는 미나보다 신중하게 일한다",
  "cmpadv-he-comparative-aff": "그는 잭보다 빠르게 달린다",
  "cmpadv-it-comparative-aff": "그것은 저것보다 빠르게 움직인다",
  "cmpadv-we-comparative-aff": "우리는 그들보다 일찍 일어난다",
  "cmpadv-they-comparative-aff": "그들은 우리보다 크게 말한다",
  "cmpadv-I-superlative-aff": "나는 우리 반에서 가장 열심히 공부한다",
  "cmpadv-she-superlative-aff": "그녀는 팀에서 가장 신중하게 일한다",
  "cmpadv-he-superlative-aff": "그는 셋 중에서 가장 빠르게 달린다",
  "cmpadv-it-superlative-aff": "그것은 셋 중에서 가장 빠르게 움직인다",
  "cmpadv-we-superlative-aff": "우리는 반에서 가장 일찍 일어난다",
  "cmpadv-they-superlative-aff": "그들은 그룹에서 가장 크게 말한다",
  "adjpron-something-pos-np": "나는 차가운 음료를 원한다",
  "adjpron-something-pos-pron": "나는 차가운 것을 원한다",
  "adjpron-somebody-pos-np": "나는 힘센 조력자가 필요하다",
  "adjpron-somebody-pos-pron": "나는 힘센 누군가가 필요하다",
  "adjpron-someone-pos-np": "그녀는 이상한 남자를 만났다",
  "adjpron-someone-pos-pron": "그녀는 이상한 누군가를 만났다",
  "adjpron-anything-pos-np": "나는 비싼 가방을 원하지 않는다",
  "adjpron-anything-pos-pron": "나는 비싼 것은 원하지 않는다",
  "adjpron-nothing-pos-np": "특별한 이유가 없다",
  "adjpron-nothing-pos-pron": "특별한 것은 아무것도 없다",
  "adjpron-everything-pos-np": "나는 달콤한 음식을 다 좋아한다",
  "adjpron-everything-pos-pron": "나는 달콤한 것은 다 좋아한다",
  "quantsome-books-there-aff": "책이 좀 있다",
  "quantsome-books-there-neg": "책이 하나도 없다",
  "quantsome-books-there-q": "책이 좀 있니?",
  "quantsome-water-there-aff": "물이 좀 있다",
  "quantsome-water-there-neg": "물이 하나도 없다",
  "quantsome-water-there-q": "물이 좀 있니?",
  "quantsome-students-there-aff": "학생이 좀 있다",
  "quantsome-students-there-neg": "학생이 하나도 없다",
  "quantsome-students-there-q": "학생이 좀 있니?",
  "quantsome-money-there-aff": "돈이 좀 있다",
  "quantsome-money-there-neg": "돈이 하나도 없다",
  "quantsome-money-there-q": "돈이 좀 있니?",
  "quantsome-questions-there-aff": "질문이 좀 있다",
  "quantsome-questions-there-neg": "질문이 하나도 없다",
  "quantsome-questions-there-q": "질문이 좀 있니?",
  "quantsome-time-there-aff": "시간이 좀 있다",
  "quantsome-time-there-neg": "시간이 하나도 없다",
  "quantsome-time-there-q": "시간이 좀 있니?",
  "quantsome-books-have-aff": "나는 책이 좀 있다",
  "quantsome-books-have-neg": "나는 책이 하나도 없다",
  "quantsome-books-have-q": "내게 책이 좀 있니?",
  "quantsome-water-have-aff": "나는 물이 좀 있다",
  "quantsome-water-have-neg": "나는 물이 하나도 없다",
  "quantsome-water-have-q": "내게 물이 좀 있니?",
  "quantsome-students-have-aff": "나는 학생이 좀 있다",
  "quantsome-students-have-neg": "나는 학생이 하나도 없다",
  "quantsome-students-have-q": "내게 학생이 좀 있니?",
  "quantsome-money-have-aff": "나는 돈이 좀 있다",
  "quantsome-money-have-neg": "나는 돈이 하나도 없다",
  "quantsome-money-have-q": "내게 돈이 좀 있니?",
  "quantsome-questions-have-aff": "나는 질문이 좀 있다",
  "quantsome-questions-have-neg": "나는 질문이 하나도 없다",
  "quantsome-questions-have-q": "내게 질문이 좀 있니?",
  "quantsome-time-have-aff": "나는 시간이 좀 있다",
  "quantsome-time-have-neg": "나는 시간이 하나도 없다",
  "quantsome-time-have-q": "내게 시간이 좀 있니?",
  "adv-I-adv-adj": "나는 느리다",
  "adv-I-adv-advb": "나는 느리게 걷는다",
  "adv-she-adv-adj": "그녀는 신중하다",
  "adv-she-adv-advb": "그녀는 신중하게 운전한다",
  "adv-he-adv-adj": "그는 빠르다",
  "adv-he-adv-advb": "그는 빠르게 달린다",
  "adv-it-adv-adj": "그것은 시끄럽다",
  "adv-it-adv-advb": "그것은 시끄럽게 울린다",
  "adv-we-adv-adj": "우리는 조용하다",
  "adv-we-adv-advb": "우리는 조용하게 말한다",
  "adv-they-adv-adj": "그들은 친절하다",
  "adv-they-adv-advb": "그들은 친절하게 웃는다",
  "warmup-tall-base-word": "키가 큰",
  "warmup-nice-base-word": "멋진",
  "warmup-happy-base-word": "행복한",
  "warmup-big-base-word": "큰",
  "warmup-beautiful-base-word": "아름다운",
  "warmup-good-base-word": "좋은",
  "warmup-bad-base-word": "나쁜",
  "warmup-many-base-word": "많은",
  "warmup-little-base-word": "적은",
  "warmup-tall-comparative-word": "더 키가 큰",
  "warmup-nice-comparative-word": "더 멋진",
  "warmup-happy-comparative-word": "더 행복한",
  "warmup-big-comparative-word": "더 큰",
  "warmup-beautiful-comparative-word": "더 아름다운",
  "warmup-good-comparative-word": "더 좋은",
  "warmup-bad-comparative-word": "더 나쁜",
  "warmup-many-comparative-word": "더 많은",
  "warmup-little-comparative-word": "더 적은",
  "warmup-tall-superlative-word": "가장 키가 큰",
  "warmup-nice-superlative-word": "가장 멋진",
  "warmup-happy-superlative-word": "가장 행복한",
  "warmup-big-superlative-word": "가장 큰",
  "warmup-beautiful-superlative-word": "가장 아름다운",
  "warmup-good-superlative-word": "가장 좋은",
  "warmup-bad-superlative-word": "가장 나쁜",
  "warmup-many-superlative-word": "가장 많은",
  "warmup-little-superlative-word": "가장 적은"
};
