// 이 파일은 scripts/generate-data.mjs 가 문장표에서 자동 생성한다. 직접 수정 금지.
// 키: `${series}-${subject}-${tense}-${form}` — 드릴 288문장 + 의문사 36문장.
export const SUBJECTS = ["I","she","he","it","we","they"];
export const FORMS = ["aff","neg","q"];
// 시제 범위 설정 UI에서 고를 수 있는 시제 (perf·modal은 세트 고유 시제라 항상 포함)
export const RANGE_TENSES = ["present","past","will","goingto"];
export const SETS = [
  {
    "id": "be",
    "label": "be동사",
    "tenses": [
      "present",
      "past",
      "will",
      "goingto"
    ],
    "pred": {
      "I": "late",
      "she": "lovely",
      "he": "busy",
      "it": "cold",
      "we": "ready",
      "they": "here"
    }
  },
  {
    "id": "verb",
    "label": "일반동사",
    "tenses": [
      "present",
      "past",
      "will",
      "goingto"
    ],
    "pred": {
      "I": "know you",
      "she": "like it",
      "he": "know it",
      "it": "work",
      "we": "need it",
      "they": "like it"
    }
  },
  {
    "id": "prog",
    "label": "진행",
    "tenses": [
      "present",
      "past"
    ],
    "pred": {
      "I": "working",
      "she": "coming",
      "he": "waiting",
      "it": "raining",
      "we": "waiting",
      "they": "coming"
    }
  },
  {
    "id": "pass",
    "label": "수동",
    "tenses": [
      "present",
      "past"
    ],
    "pred": {
      "I": "invited",
      "she": "invited",
      "he": "invited",
      "it": "broken",
      "we": "invited",
      "they": "invited"
    }
  },
  {
    "id": "perfbe",
    "label": "완료 be",
    "tenses": [
      "perf"
    ],
    "pred": {
      "I": "busy",
      "she": "busy",
      "he": "busy",
      "it": "cold",
      "we": "busy",
      "they": "here"
    }
  },
  {
    "id": "perfverb",
    "label": "완료 일반",
    "tenses": [
      "perf"
    ],
    "pred": {
      "I": "seen it",
      "she": "seen it",
      "he": "seen it",
      "it": "worked",
      "we": "seen it",
      "they": "seen it"
    }
  },
  {
    "id": "can",
    "label": "can",
    "tenses": [
      "modal"
    ],
    "pred": {
      "I": "do it",
      "she": "come",
      "he": "help",
      "it": "wait",
      "we": "go",
      "they": "help"
    }
  },
  {
    "id": "should",
    "label": "should",
    "tenses": [
      "modal"
    ],
    "pred": {
      "I": "go",
      "she": "come",
      "he": "wait",
      "it": "be ready",
      "we": "go",
      "they": "come"
    }
  }
];
export const SENTENCES = {
  "be-I-present-aff": "I am late.",
  "be-I-present-neg": "I'm not late.",
  "be-I-present-q": "Am I late?",
  "be-she-present-aff": "She is lovely.",
  "be-she-present-neg": "She isn't lovely.",
  "be-she-present-q": "Is she lovely?",
  "be-he-present-aff": "He is busy.",
  "be-he-present-neg": "He isn't busy.",
  "be-he-present-q": "Is he busy?",
  "be-it-present-aff": "It is cold.",
  "be-it-present-neg": "It isn't cold.",
  "be-it-present-q": "Is it cold?",
  "be-we-present-aff": "We are ready.",
  "be-we-present-neg": "We aren't ready.",
  "be-we-present-q": "Are we ready?",
  "be-they-present-aff": "They are here.",
  "be-they-present-neg": "They aren't here.",
  "be-they-present-q": "Are they here?",
  "be-I-past-aff": "I was late.",
  "be-I-past-neg": "I wasn't late.",
  "be-I-past-q": "Was I late?",
  "be-she-past-aff": "She was lovely.",
  "be-she-past-neg": "She wasn't lovely.",
  "be-she-past-q": "Was she lovely?",
  "be-he-past-aff": "He was busy.",
  "be-he-past-neg": "He wasn't busy.",
  "be-he-past-q": "Was he busy?",
  "be-it-past-aff": "It was cold.",
  "be-it-past-neg": "It wasn't cold.",
  "be-it-past-q": "Was it cold?",
  "be-we-past-aff": "We were ready.",
  "be-we-past-neg": "We weren't ready.",
  "be-we-past-q": "Were we ready?",
  "be-they-past-aff": "They were here.",
  "be-they-past-neg": "They weren't here.",
  "be-they-past-q": "Were they here?",
  "be-I-will-aff": "I'll be late.",
  "be-I-will-neg": "I won't be late.",
  "be-I-will-q": "Will I be late?",
  "be-she-will-aff": "She'll be fine.",
  "be-she-will-neg": "She won't be fine.",
  "be-she-will-q": "Will she be fine?",
  "be-he-will-aff": "He'll be busy.",
  "be-he-will-neg": "He won't be busy.",
  "be-he-will-q": "Will he be busy?",
  "be-it-will-aff": "It'll be cold.",
  "be-it-will-neg": "It won't be cold.",
  "be-it-will-q": "Will it be cold?",
  "be-we-will-aff": "We'll be ready.",
  "be-we-will-neg": "We won't be ready.",
  "be-we-will-q": "Will we be ready?",
  "be-they-will-aff": "They'll be here.",
  "be-they-will-neg": "They won't be here.",
  "be-they-will-q": "Will they be here?",
  "be-I-goingto-aff": "I'm going to be late.",
  "be-I-goingto-neg": "I'm not going to be late.",
  "be-I-goingto-q": "Am I going to be late?",
  "be-she-goingto-aff": "She's going to be fine.",
  "be-she-goingto-neg": "She isn't going to be fine.",
  "be-she-goingto-q": "Is she going to be fine?",
  "be-he-goingto-aff": "He's going to be busy.",
  "be-he-goingto-neg": "He isn't going to be busy.",
  "be-he-goingto-q": "Is he going to be busy?",
  "be-it-goingto-aff": "It's going to be cold.",
  "be-it-goingto-neg": "It isn't going to be cold.",
  "be-it-goingto-q": "Is it going to be cold?",
  "be-we-goingto-aff": "We're going to be ready.",
  "be-we-goingto-neg": "We aren't going to be ready.",
  "be-we-goingto-q": "Are we going to be ready?",
  "be-they-goingto-aff": "They're going to be here.",
  "be-they-goingto-neg": "They aren't going to be here.",
  "be-they-goingto-q": "Are they going to be here?",
  "verb-I-present-aff": "I know you.",
  "verb-I-present-neg": "I don't know you.",
  "verb-I-present-q": "Do I know you?",
  "verb-she-present-aff": "She likes it.",
  "verb-she-present-neg": "She doesn't like it.",
  "verb-she-present-q": "Does she like it?",
  "verb-he-present-aff": "He knows it.",
  "verb-he-present-neg": "He doesn't know it.",
  "verb-he-present-q": "Does he know it?",
  "verb-it-present-aff": "It works.",
  "verb-it-present-neg": "It doesn't work.",
  "verb-it-present-q": "Does it work?",
  "verb-we-present-aff": "We need it.",
  "verb-we-present-neg": "We don't need it.",
  "verb-we-present-q": "Do we need it?",
  "verb-they-present-aff": "They like it.",
  "verb-they-present-neg": "They don't like it.",
  "verb-they-present-q": "Do they like it?",
  "verb-I-past-aff": "I knew you.",
  "verb-I-past-neg": "I didn't know you.",
  "verb-I-past-q": "Did I know you?",
  "verb-she-past-aff": "She liked it.",
  "verb-she-past-neg": "She didn't like it.",
  "verb-she-past-q": "Did she like it?",
  "verb-he-past-aff": "He knew it.",
  "verb-he-past-neg": "He didn't know it.",
  "verb-he-past-q": "Did he know it?",
  "verb-it-past-aff": "It worked.",
  "verb-it-past-neg": "It didn't work.",
  "verb-it-past-q": "Did it work?",
  "verb-we-past-aff": "We needed it.",
  "verb-we-past-neg": "We didn't need it.",
  "verb-we-past-q": "Did we need it?",
  "verb-they-past-aff": "They liked it.",
  "verb-they-past-neg": "They didn't like it.",
  "verb-they-past-q": "Did they like it?",
  "verb-I-will-aff": "I'll see you.",
  "verb-I-will-neg": "I won't see you.",
  "verb-I-will-q": "Will I see you?",
  "verb-she-will-aff": "She'll like it.",
  "verb-she-will-neg": "She won't like it.",
  "verb-she-will-q": "Will she like it?",
  "verb-he-will-aff": "He'll come.",
  "verb-he-will-neg": "He won't come.",
  "verb-he-will-q": "Will he come?",
  "verb-it-will-aff": "It'll work.",
  "verb-it-will-neg": "It won't work.",
  "verb-it-will-q": "Will it work?",
  "verb-we-will-aff": "We'll need it.",
  "verb-we-will-neg": "We won't need it.",
  "verb-we-will-q": "Will we need it?",
  "verb-they-will-aff": "They'll like it.",
  "verb-they-will-neg": "They won't like it.",
  "verb-they-will-q": "Will they like it?",
  "verb-I-goingto-aff": "I'm going to see you.",
  "verb-I-goingto-neg": "I'm not going to see you.",
  "verb-I-goingto-q": "Am I going to see you?",
  "verb-she-goingto-aff": "She's going to like it.",
  "verb-she-goingto-neg": "She isn't going to like it.",
  "verb-she-goingto-q": "Is she going to like it?",
  "verb-he-goingto-aff": "He's going to come.",
  "verb-he-goingto-neg": "He isn't going to come.",
  "verb-he-goingto-q": "Is he going to come?",
  "verb-it-goingto-aff": "It's going to work.",
  "verb-it-goingto-neg": "It isn't going to work.",
  "verb-it-goingto-q": "Is it going to work?",
  "verb-we-goingto-aff": "We're going to need it.",
  "verb-we-goingto-neg": "We aren't going to need it.",
  "verb-we-goingto-q": "Are we going to need it?",
  "verb-they-goingto-aff": "They're going to like it.",
  "verb-they-goingto-neg": "They aren't going to like it.",
  "verb-they-goingto-q": "Are they going to like it?",
  "prog-I-present-aff": "I'm working.",
  "prog-I-present-neg": "I'm not working.",
  "prog-I-present-q": "Am I working?",
  "prog-she-present-aff": "She's coming.",
  "prog-she-present-neg": "She isn't coming.",
  "prog-she-present-q": "Is she coming?",
  "prog-he-present-aff": "He's waiting.",
  "prog-he-present-neg": "He isn't waiting.",
  "prog-he-present-q": "Is he waiting?",
  "prog-it-present-aff": "It's raining.",
  "prog-it-present-neg": "It isn't raining.",
  "prog-it-present-q": "Is it raining?",
  "prog-we-present-aff": "We're waiting.",
  "prog-we-present-neg": "We aren't waiting.",
  "prog-we-present-q": "Are we waiting?",
  "prog-they-present-aff": "They're coming.",
  "prog-they-present-neg": "They aren't coming.",
  "prog-they-present-q": "Are they coming?",
  "prog-I-past-aff": "I was working.",
  "prog-I-past-neg": "I wasn't working.",
  "prog-I-past-q": "Was I working?",
  "prog-she-past-aff": "She was coming.",
  "prog-she-past-neg": "She wasn't coming.",
  "prog-she-past-q": "Was she coming?",
  "prog-he-past-aff": "He was waiting.",
  "prog-he-past-neg": "He wasn't waiting.",
  "prog-he-past-q": "Was he waiting?",
  "prog-it-past-aff": "It was raining.",
  "prog-it-past-neg": "It wasn't raining.",
  "prog-it-past-q": "Was it raining?",
  "prog-we-past-aff": "We were waiting.",
  "prog-we-past-neg": "We weren't waiting.",
  "prog-we-past-q": "Were we waiting?",
  "prog-they-past-aff": "They were coming.",
  "prog-they-past-neg": "They weren't coming.",
  "prog-they-past-q": "Were they coming?",
  "pass-I-present-aff": "I am invited.",
  "pass-I-present-neg": "I'm not invited.",
  "pass-I-present-q": "Am I invited?",
  "pass-she-present-aff": "She is invited.",
  "pass-she-present-neg": "She isn't invited.",
  "pass-she-present-q": "Is she invited?",
  "pass-he-present-aff": "He is invited.",
  "pass-he-present-neg": "He isn't invited.",
  "pass-he-present-q": "Is he invited?",
  "pass-it-present-aff": "It is broken.",
  "pass-it-present-neg": "It isn't broken.",
  "pass-it-present-q": "Is it broken?",
  "pass-we-present-aff": "We are invited.",
  "pass-we-present-neg": "We aren't invited.",
  "pass-we-present-q": "Are we invited?",
  "pass-they-present-aff": "They are invited.",
  "pass-they-present-neg": "They aren't invited.",
  "pass-they-present-q": "Are they invited?",
  "pass-I-past-aff": "I was invited.",
  "pass-I-past-neg": "I wasn't invited.",
  "pass-I-past-q": "Was I invited?",
  "pass-she-past-aff": "She was invited.",
  "pass-she-past-neg": "She wasn't invited.",
  "pass-she-past-q": "Was she invited?",
  "pass-he-past-aff": "He was invited.",
  "pass-he-past-neg": "He wasn't invited.",
  "pass-he-past-q": "Was he invited?",
  "pass-it-past-aff": "It was broken.",
  "pass-it-past-neg": "It wasn't broken.",
  "pass-it-past-q": "Was it broken?",
  "pass-we-past-aff": "We were invited.",
  "pass-we-past-neg": "We weren't invited.",
  "pass-we-past-q": "Were we invited?",
  "pass-they-past-aff": "They were invited.",
  "pass-they-past-neg": "They weren't invited.",
  "pass-they-past-q": "Were they invited?",
  "perfbe-I-perf-aff": "I have been busy.",
  "perfbe-I-perf-neg": "I haven't been busy.",
  "perfbe-I-perf-q": "Have I been busy?",
  "perfbe-she-perf-aff": "She has been busy.",
  "perfbe-she-perf-neg": "She hasn't been busy.",
  "perfbe-she-perf-q": "Has she been busy?",
  "perfbe-he-perf-aff": "He has been busy.",
  "perfbe-he-perf-neg": "He hasn't been busy.",
  "perfbe-he-perf-q": "Has he been busy?",
  "perfbe-it-perf-aff": "It has been cold.",
  "perfbe-it-perf-neg": "It hasn't been cold.",
  "perfbe-it-perf-q": "Has it been cold?",
  "perfbe-we-perf-aff": "We have been busy.",
  "perfbe-we-perf-neg": "We haven't been busy.",
  "perfbe-we-perf-q": "Have we been busy?",
  "perfbe-they-perf-aff": "They have been here.",
  "perfbe-they-perf-neg": "They haven't been here.",
  "perfbe-they-perf-q": "Have they been here?",
  "perfverb-I-perf-aff": "I have seen it.",
  "perfverb-I-perf-neg": "I haven't seen it.",
  "perfverb-I-perf-q": "Have I seen it?",
  "perfverb-she-perf-aff": "She has seen it.",
  "perfverb-she-perf-neg": "She hasn't seen it.",
  "perfverb-she-perf-q": "Has she seen it?",
  "perfverb-he-perf-aff": "He has seen it.",
  "perfverb-he-perf-neg": "He hasn't seen it.",
  "perfverb-he-perf-q": "Has he seen it?",
  "perfverb-it-perf-aff": "It has worked.",
  "perfverb-it-perf-neg": "It hasn't worked.",
  "perfverb-it-perf-q": "Has it worked?",
  "perfverb-we-perf-aff": "We have seen it.",
  "perfverb-we-perf-neg": "We haven't seen it.",
  "perfverb-we-perf-q": "Have we seen it?",
  "perfverb-they-perf-aff": "They have seen it.",
  "perfverb-they-perf-neg": "They haven't seen it.",
  "perfverb-they-perf-q": "Have they seen it?",
  "can-I-modal-aff": "I can do it.",
  "can-I-modal-neg": "I can't do it.",
  "can-I-modal-q": "Can I do it?",
  "can-she-modal-aff": "She can come.",
  "can-she-modal-neg": "She can't come.",
  "can-she-modal-q": "Can she come?",
  "can-he-modal-aff": "He can help.",
  "can-he-modal-neg": "He can't help.",
  "can-he-modal-q": "Can he help?",
  "can-it-modal-aff": "It can wait.",
  "can-it-modal-neg": "It can't wait.",
  "can-it-modal-q": "Can it wait?",
  "can-we-modal-aff": "We can go.",
  "can-we-modal-neg": "We can't go.",
  "can-we-modal-q": "Can we go?",
  "can-they-modal-aff": "They can help.",
  "can-they-modal-neg": "They can't help.",
  "can-they-modal-q": "Can they help?",
  "should-I-modal-aff": "I should go.",
  "should-I-modal-neg": "I shouldn't go.",
  "should-I-modal-q": "Should I go?",
  "should-she-modal-aff": "She should come.",
  "should-she-modal-neg": "She shouldn't come.",
  "should-she-modal-q": "Should she come?",
  "should-he-modal-aff": "He should wait.",
  "should-he-modal-neg": "He shouldn't wait.",
  "should-he-modal-q": "Should he wait?",
  "should-it-modal-aff": "It should be ready.",
  "should-it-modal-neg": "It shouldn't be ready.",
  "should-it-modal-q": "Should it be ready?",
  "should-we-modal-aff": "We should go.",
  "should-we-modal-neg": "We shouldn't go.",
  "should-we-modal-q": "Should we go?",
  "should-they-modal-aff": "They should come.",
  "should-they-modal-neg": "They shouldn't come.",
  "should-they-modal-q": "Should they come?"
};
export const WH = [
  {
    "id": "whbe",
    "label": "be동사",
    "cols": [
      "Where",
      "When",
      "Why"
    ],
    "rows": {
      "I": [
        "Where am I?",
        "When am I free?",
        "Why am I here?"
      ],
      "she": [
        "Where is she?",
        "When is she coming?",
        "Why is she late?"
      ],
      "he": [
        "Where is he?",
        "When is he coming?",
        "Why is he angry?"
      ],
      "it": [
        "Where is it?",
        "When is it?",
        "Why is it cold?"
      ],
      "we": [
        "Where are we?",
        "When are we leaving?",
        "Why are we here?"
      ],
      "they": [
        "Where are they?",
        "When are they coming?",
        "Why are they here?"
      ]
    }
  },
  {
    "id": "whdo",
    "label": "do / does",
    "cols": [
      "What",
      "How",
      "Why"
    ],
    "rows": {
      "I": [
        "What do I do?",
        "How do I know?",
        "Why do I need it?"
      ],
      "she": [
        "What does she want?",
        "How does she know?",
        "Why does she like it?"
      ],
      "he": [
        "What does he want?",
        "How does he do it?",
        "Why does he need it?"
      ],
      "it": [
        "What does it mean?",
        "How does it work?",
        "Why does it matter?"
      ],
      "we": [
        "What do we need?",
        "How do we get there?",
        "Why do we need it?"
      ],
      "they": [
        "What do they want?",
        "How do they know?",
        "Why do they like it?"
      ]
    }
  }
];
